### ISSUE TITLE
new ESpeak variants wider variety of speaking styles

### ISSUE THREAD

**Issue by joshknnd1982** [espeak-ng/espeak-ng#1016]
Could someone in charge of voice variants add new tunes statements to the ESpeak intonation file to both emulate other tts engines speaking styles and also make new and different voices with different speaking styles, based on additional tunes statements? I would like to have an ESpeak voice that speaks with the inflections of doubleTalk or trippleTalk speech, another that speaks with Keynote gold intonation style, and perhaps another with a similar intonation style to infovox230 or dolphin orpheus. Perhaps other ESpeak voices that sing the text in some way or have other speaking styles based on new tunes statements. with espeak sapi5 you would open the intonations source file in notepad, add new tunes statements, recompile, then make a new voice variant file with the new tunes statements added at the end such as, "tunes s8, c8, e8, q8".

**Comment by valdisvi** [comment]
Intonation of eSpeak NG voices is described in [Intonation](https://github.com/espeak-ng/espeak-ng/blob/master/docs/intonation.md) page. I don't know how specifics for mentioned tools, but due to technological differences, possibility to mimic voice of one tool as voice of another is quite improbable. Just read basics of e.g. [eSpeakNG](https://en.wikipedia.org/wiki/ESpeak), [MBROLA](https://en.wikipedia.org/wiki/MBROLA) and [Klatt](https://www.fon.hum.uva.nl/david/ma_ssp/doc/Klatt-1990-JAS000820.pdf).

**Comment by joshknnd1982** [comment]
It wouldn’t mimmick the actual voice, just the intonations of that voice. 


Sent from Mail for Windows

**Comment by joshknnd1982** [comment]
Ok, so how do I run the:

espeak-ng --compile-intonations

how do I run that command? I am using windows10 with a compiled Espeak-ng as part of NVDA screen reader.




Sent from Mail for Windows

**Comment by valdisvi** [comment]
https://docs.microsoft.com/en-us/windows/terminal/get-started

**Comment by 118dz** [comment]
why i can't find espeak-ng but i fund espeak  What's the difference between

**Comment by valdisvi** [comment]
> why i can't find espeak-ng but i fund espeak What's the difference between

https://en.wikipedia.org/wiki/ESpeak#History
