### ISSUE TITLE
mbrola not working!!

### ISSUE THREAD

**Issue by A-d-DASARE** [espeak-ng/espeak-ng#1089]
mbrola: FATAL ERROR : cannot find file /usr/share/mbrola/us1/us1 !
mbrowrap error: mbrola exited with status 216
mbrola voice not found

**Comment by valdisvi** [comment]
MBROLA works as expected. It says that  /usr/share/mbrola/us1/us1 is not found what is data file for selected voice. Check that you have installed [MBROLA voices](https://github.com/numediart/MBROLA-voices/).

**Comment by A-d-DASARE** [comment]
Thanks!! will check

Regards,
ASHWINI DASARE

**Comment by KrAG2000** [comment]
@A-d-DASARE , this issue was solved by correcting the path manually using following steps.

1-> Copy the folder named "mbrola" located at "/usr/share/espeak-data" and paste it inside "/usr/share"
2-> Copy the folder named "voices" located at "/usr/share/espeak-data" and paste it inside "/usr/share/mbrola"
3-> Lastly, put the file (en1 or if any other) that you downloaded in step 5, inside "/usr/share/mbrola/voices"
(Path which was giving the error is now actually there, so no error!)
