### ISSUE TITLE
about espeak edit and exe file 

### ISSUE THREAD

**Issue by shadyar** [espeak-ng/espeak-ng#110]
@rhdunn 
Hello R.H Dunn
in source forge project there was a suitable program named "e-Speak edit" it is used analyzing rules, checking phonemes strings, considering decision processes and etc
it seems in e-Speak-ng project, speak edit developing is not continued.
1. do you want to develop e-speak edit?
2. how do we programmer analyze rules and decisions of a language?
3. in e-speak project there is exe file of espeak for microsoft windows SAPI-5 that users can easily install and use it, could you please release exe file of espeak-ng SAPI-5 of new versions?

regards

**Comment by shadyar** [comment]
rhdunn

**Comment by rhdunn** [comment]
1. espeakedit will be rebuilt to be more flexible and powerful (issue #3). The part of espeakedit responsible for building the phoneme and intonation data has moved into the main espeak-ng project, to make it easy to build espeak-ng without wxWindows or other GUI library.

2. To build the dictionary use `make LANG` or ```ESPEAK_DATA_PATH=`pwd` src/espeak-ng --compile=LANG```. To analyse the pronunciation of a word, use ```ESPEAK_DATA_PATH=`pwd` src/espeak-ng -X WORD```, e.g.:

        $ espeak-ng -X hai
        Translate 'hai'
          1	h        [h]

         57	ai (_    [aI]
         36	ai       [eI]
          1	a        [a]

        h'aI

3. espeak-ng has a Windows build that provides audio from the command line (like the Linux version). You can currently build this with Visual Studio and I will release an installer when it is ready. The SAPI support is being reworked due to licensing issues (issue #7), and will be improved in time. Basic SAPI support is working and will be available with the Windows installer when it is ready.
