### ISSUE TITLE
Espeak-ng stutters when reading live on Windows

### ISSUE THREAD

**Issue by Exink** [espeak-ng/espeak-ng#1190]
Hey there,

I don't know where should I post this, so if you have any other ideas please let me know and I will remove this issue.

I installed ESpeak-NG on my Windows 10 laptop and I don't have any problem using it through the C MD, but when I want to read some live text by entering for example `ESpeak-NG "Hello"`, the software reads the words aloud but the voice stutters, like if you kept holding the spacebar whilst reproducing the spoken words. When you save those words in a wav file the problem is gone, however. I closed the vast majority of windows and this is still happening.

I read that this problem also happens in some raspberry pi machines, but I have no found a solution for this problem on windows.

Can you tell me what could I do to solve this issue?

Thanks!

**Comment by zment4** [comment]
I have the same problem. Live reading produces choppy audio (on my relatively beefy desktop no less) on Windows 10, but the wave file is generated flawlessly.

**Comment by zment4** [comment]
I figured out an ugly workaround. In pcaudiolib xaudio2.cpp, just create a new backing buffer for all audio data, and don't wait for the audio to be played. The stuttering was because the pcaudiolib waits until all audio data has been played before presenting new data.

I moved this
```cpp
	while (true)
	{
		Sleep(10);

		XAUDIO2_VOICE_STATE state = { 0 };
		self->source->GetState(&state);
		if (state.pCurrentBufferContext == NULL && state.BuffersQueued == 0)
			break;
	}
```
from `xaudio2_object_write()` to `xaudio2_object_drain()` so it waits to output all the available audio before quitting, and stops blocking the `xaudio2_object_write()`. And in `xaudio2_object_write()` I added:
```cpp
	BYTE* buf_data = (BYTE *)malloc(bytes);
	memcpy(buf_data, data, bytes);

	XAUDIO2_BUFFER buffer = {0};
	buffer.AudioBytes = bytes;
	buffer.pAudioData = buf_data;
```

It's ugly because it never frees the malloced audio buffer bytes. For now it works as a workaround, but I'd rather either figure out a way to free that memory after a buffer has been played back through the audio interface (maybe some callback somewhere?) or maybe if there are helper functions in XAudio2 itself that handles audio buffer allocation and freeing after playing?

**Comment by zment4** [comment]
XAudio2 seems to have an OnBufferEnd callback, exactly for this purpose...

**Comment by zment4** [comment]
Tested it out, added callback that free's the manually allocated memory, and also blocks in case the XAudio SourceVoice doesn't want to get any more buffers in. Without the blocking then XAudio SourceVoice gets to its buffer limit, a bunch of the audio buffers will just be skipped. I'll put a PR for pcaudiolib on espeak-ng for the fix and link it here.
