### ISSUE TITLE
Spanishç

### ISSUE THREAD

**Issue by sukiletxe** [espeak-ng/espeak-ng#130]
The ç in Spanish is pronounced as /k/, and it should be pronounced as /s/.

**Comment by Christianlm** [comment]
Since XVIII century the ç character is not included in spanish alphabet, but I need more source about this.
However I agree, you  can find this character in words of old spanish language.
 In north Spain this character was pronunced /θ/, in south wos pronunced with a phoneme callled in Spanish "ese coronal".
For example, the phoneme /θ/ is used in spanish words  as "celo" "cerrar" etc.
the phoneme /s/ in "señor" "salir".
Which phoneme is more correct for  "ce cedilla"in your opinion?
Thanks.

**Comment by sukiletxe** [comment]
Let's stick with the other synthesizers conventions and make it pronounce as /s/.

**Comment by Christianlm** [comment]
I agree, thanks. Then phoneme /s/ will be pronunced for ç in spanish language.

As far as I know only the commercial Eloquence in latin american spanish pronunces /θ/ for "ç".
