### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by luiscarlos2000** [espeak-ng/espeak-ng#1323]
Not a developer, well a programmer I could be, but since I'm digging through the linguistic world of minority and constructed languages. I want eSpeakNG to support the following languages. If I want to create some model I should, however university will somehow take out my time on adding those.
Note. I'm not a first or second language speaker nor writer in the languages mentioned.
1. Anglo-Saxon (old english)
2. Arromanian
3. Asturian
4. Breton
5. Cornish
6. Corsican
7. Faroese
8. Frisian (mostely West frisian, could also add North and East (Saterland) Frisian)
9. Franco-Provençal (Arpitan)
10. Friulian
11. Galician
12. Gothic
13. Interlingue (previously Occidental)
14. Jamaican Creole
15. Judaeo-Spanish (Ladino) this is somehow special and interesting. being a Jewish language, uses the hebrew alphabet, but also the latin alphabet with many versions of them. I propose basing it on the spanish alphabet, but I don't know your opinion.
16. Kotava
17. Ladin
18. Ligurian
19. Manx
20. Mirandese
21. Neapolitan
22. Novial
23. Occitan (including dialects)
24. Old Norse
25. Romanch (mainly the pan-variety Rumantsch Grischun, could also add dialects (idioms))
26. Sardinian
27. Scots
28. Sicilian
29. Talossan (This is also interesting, since the first time that a micronational language is added.)
30. Venetian
31. Volapük
32. Walloon
33. Yiddish

**Comment by Sergiaws** [comment]
I'm totally agree with that. I wish to add the Zulu language, however, some of the zulu clicks sounds a bit strange for me, since I'm not south African. Is important to remember some phonetic exceptions. Regarding Judeospanish, it should be similar to Spanish, but, as far as I know, you just would need to change the pronunciation of the j letter, so it would sound like it sounds in french, and change the pronunciation of z so it would sound as it sounds in french too. Regarding Gothic, it also is represented using latin alphabet and Gothic one's.

**Comment by jaacoppi** [comment]
See https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md for instructions.
