### ISSUE TITLE
Incorrect pronunciation of several Malayalam (ML) sounds

### ISSUE THREAD

**Issue by Qchristensen** [espeak-ng/espeak-ng#1507]
This was reported from an NVDA user:

The user has recently updated to NVDA Version: 2022.3.1 (using eSpeak-NG 1.52-dev commit 9de65fcb)
They were previously using NVDA 2022.2.2 (using eSpeak-NG 1.51-dev commit 7e5457f91e10)

They are using the Espeak-NG Denis voice.

They advised that the following letters were previously pronounced correctly but now are not:
1. ക: The currect sound is "ka" and not "Ga".
2. ത: Currect sound is "tha" and not "da".
3. പ: Currect sound is "pa" and not "ba".

**Comment by Ziyadsiya** [comment]
Incorrect pronunciation of several Malayalam (ML) sounds:
Not only with Espeak-NG Denis voice, I'm using Espeak-NG NVDA Robert variant. It has also, have lots of wrong pronounciation with Malayalam letters. the following letters were previously pronounced correctly but now are not:
1. ക: The currect sound is "ka" and not "Ga".
2. ത: Currect sound is "tha" and not "da".
3. പ: Currect sound is "pa" and not "ba".
Due to this wrong pronounciation, the words which are beginning with these letters are also miss prounouncing now. E.G,
കേരളം: it says ഗേരളം.
താമര: it says ദാമര.
പോലെ: it says ബോലെ.
Like these words, there are a lots of Malayalam words are pronouncing by the latest NVDA. There is not any other TTS other  than Espeak TTS available to read Malayalam within a proper structure. So, the wrong pronunciation is making lots of trouble for the computer users from Kerala.

**Comment by jaacoppi** [comment]
According to git bisect the problem is here:
commit 34a12c83b46b51373ae134a12c83b46b51373ae183c3fb8fcce990414a05 (HEAD)83c3fb8fcce990414a05 (HEAD)
Author: Samuel Thibault <samuel.thibault@ens-lyon.org>
Date:   Tue Mar 15 18:17:42 2022 +0100
 IsLetterGroup: Do not blindly walk back in the word

@sthibaul any ideas? Clearly this commit is also necessary and should not be reverted.

**Comment by sthibaul** [comment]
that's very odd indeed, we shouldn't be needing to walk back past the beginning of the string... Perhaps we should first create a test case that exhibits the behavior, check that the reversion fixes the pronunciation issue at stake, and then observe why the pronunciation would need to walk back that way.

**Comment by jaacoppi** [comment]
I'm pretty sure ti's here:
https://github.com/espeak-ng/espeak-ng/blob/63f653c99231784b488ccd08dc076aaddb19b30c/src/libespeak-ng/dictionary.c#L1864

The current broken functionality returns -1. Apparently it never should.

**Comment by sthibaul** [comment]
Thanks for the testcase, I could see what's wrong, will submit a PR
