### ISSUE TITLE
The spacing between letters should not decrease in  Turkish

### ISSUE THREAD

**Issue by burakyuksek** [espeak-ng/espeak-ng#229]
I thank you for applying the fix about Turkish double letters. Unfortunately an issue has popped up. When the voice speeds up, the spacing between double letters  decrease and eventually the word gitti begins to sound like giti. Can you please make it so the spacing between those double  letters not increase?Thank you.

**Comment by valdisvi** [comment]
Solution could be using two different pauses together _long_ ```_::```  or _medium_ one ```_:``` with _non-shortened/mandatory_ pause ```_!``` instead of current  _long_ pause ```_::```.
Does [this example](http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-x&text=%5B%5BJI_%3A_%21t%27I%5D%5D%2C+%5B%5BJI_%3A_%21t%27I%5D%5D%2C+%5B%5BJI_%3A_%21t%27I%5D%5D.&formmethod=get) sounds better with different speeds?
If yes, what combination is better for spelling: ```_::_!``` or ```_:_!```?
(I believe long pause with mandatory pause is too long, therefore medium with mandatory sounds better).

**Comment by valdisvi** [comment]
I decided to implement 2nd option, which can be tested [here](http://odo.lv/Espeak?language=en&eslang=-vtr). Please reopen issue, if it is not acceptable.
