### ISSUE TITLE
Question about Manipuri language

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#238]
Hi!
I have a question.
What language 'Manipuri' do You worked on? Because, there are two. Meitei, or Bishnupriya manipuri.
Meitei is Sino-tibetan, but Bishnupriyamanipuri is Indic language. Please, could You reply on It? Because Meitei language hasn't alphabet and I think, that this is Bishnupriya manipuri, which is written in Bengali script.
Thank You!
Marco

**Comment by rhdunn** [comment]
Thanks for clarifying the distinction between the two languages. The supported language is Bishnupriya Manipuri, which I have pushed a code change to reflect, due to the use of the Bengali script in the language files.

__NOTE:__ Meitei uses the Meitei (Meetei Mayek) script according to Wikipedia, which is suppoted in Unicode.

**Comment by Giovani93** [comment]
OK, but I have also noticed, that Meitei is switched to Bengali script also and nextly, when I have tested It, there are numbers, which are not of indoarian origin, like Bengali. So, I have made misstake also, this is Meitei and not Bishnupriya manipuri.
Big sorry for that.
