### ISSUE TITLE
Failing to compile espeak-ng.js with emscripten under MacOS

### ISSUE THREAD

**Issue by BenTalagan** [espeak-ng/espeak-ng#243]
Hi all, I've tried to compile espeak-ng.js with emscripten under MacOS but failed (whereas standard compilation of the espeak-ng binary works perfectly).

My emscripten is installed with homebrew.

During the emconfigure step (step 4 in README.md), I get some warnings and errors :

```
checking if /usr/local/Cellar/emscripten/1.37.1/libexec/emcc supports -fno-rtti -fno-exceptions... yes
checking for /usr/local/Cellar/emscripten/1.37.1/libexec/emcc option to produce PIC... -fno-common -DPIC
checking if /usr/local/Cellar/emscripten/1.37.1/libexec/emcc PIC flag -fno-common -DPIC works... yes
checking if /usr/local/Cellar/emscripten/1.37.1/libexec/emcc static flag -static works... yes
checking if /usr/local/Cellar/emscripten/1.37.1/libexec/emcc supports -c -o file.o... yes
checking if /usr/local/Cellar/emscripten/1.37.1/libexec/emcc supports -c -o file.o... (cached) yes
checking whether the /usr/local/Cellar/emscripten/1.37.1/libexec/emcc linker (/usr/local/Cellar/emscripten/1.37.1/libexec/emcc) supports shared libraries... clang version 3.9.0  (emscripten 1.37.1 : 1.37.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /usr/local/Cellar/emscripten/1.37.1/libexec/llvm/bin
WARNING:root:did not see a source tree above or next to the LLVM root directory (guessing based on directory of /usr/local/Cellar/emscripten/1.37.1/libexec/llvm/bin/llc), could not verify version numbers match
INFO:root:(Emscripten: Running sanity checks)
yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
darwin16.5.0 dyld
```
But emconfigure goes to the end of the process.

After, that, when trying to ```emmake make src/libespeak-ng.la``` I get the following errors at the end :

```
...
  CC       src/libespeak-ng/src_libespeak_ng_la-wavegen.lo
  CC       src/libespeak-ng/src_libespeak_ng_la-klatt.lo
  CCLD     src/libespeak-ng.la
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-case.o is not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-categories.o is not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-ctype.o is not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-scripts.o is not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-tostring.o is not valid LLVM bitcode
WARNING:root:src/libespeak-ng/.libs/src_libespeak_ng_la-ieee80.o is not valid LLVM bitcode
WARNING:root:Dynamic libraries (.so, .dylib, .dll) are currently not supported by Emscripten. For build system emulation purposes, Emscripten will now generate a static library file (.bc) with the suffix '.dylib'. For best practices, please adapt your build system to directly generate a static LLVM bitcode library by setting the output suffix to '.bc.')
```

And at step 5, I get :

```
emmake make

python /usr/local/Cellar/emscripten/1.37.1/libexec/tools/webidl_binder.py espeakng_glue.idl glue
/usr/local/Cellar/emscripten/1.37.1/libexec/em++ -O3 -DESPEAK_DATA_PATH=\"/usr/share/espeak-ng-data\" -I ./ -I ../ -I ../src/include/espeak-ng   -c -o espeakng_glue.o espeakng_glue.cpp
make: *** No rule to make target `../src/.libs/libespeak-ng.so', needed by `js/espeakng.worker.js'.  Stop.
```

 I'm not familiar at all with emscripten, and it's hard for me to understand what's going wrong here. Thanks by advance!

**Comment by pettarin** [comment]
Hi, just to say that I have a broken build too (I'm on Debian), with different errors but referring to ucd-tools as well. So I guess the culprit is there, but I haven't had the time to investigate the issue yet.

Also, the code might be in flux right now (I see the last commit is two days ago, and it touched ucd-tools ...)

If you just needed to get the JS build artifacts, you can download a slightly old version as described in:  https://github.com/espeak-ng/espeak-ng/tree/master/emscripten#download

**Comment by BenTalagan** [comment]
Thanks, @pettarin !

Looks like latest version breaks also on MacOS (this time during the compilation of espeak-ng itself).

```bash
src/libespeak-ng/tokenizer.c:39:2: error: use of undeclared identifier 'ucd_category'
        ucd_category cat = ucd_lookup_category(c);
```


My needs are currently satisfied with my fork/updated version of the [speak.js](https://github.com/kripken/speak.js) project, so I'm not blocked at all for the moment.

**Comment by rhdunn** [comment]
I've pushed a fix for the espeak compilation issue with the missing `ucd_category` identifier. I'm not sure if this is a MacOS or emscripten build issue as I am not seeing it locally.

**Comment by BenTalagan** [comment]
@rhdunn , thanks, the `ucd_category` bug is now fixed. I'm still having the same behaviour  as before concerning the emscripten compilation.

**Comment by pettarin** [comment]
I confirm the fix of the undeclared identifier error.

emscripten generates the following warnings at the end of step 4:

```
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-case.o is not 
valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-categories.o is 
not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-ctype.o is not 
valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-proplist.o is 
not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-scripts.o is 
not valid LLVM bitcode
WARNING:root:src/ucd-tools/src/.libs/src_libespeak_ng_la-tostring.o is 
not valid LLVM bitcode
WARNING:root:src/libespeak-ng/.libs/src_libespeak_ng_la-ieee80.o is not 
valid LLVM bitcode
```

and, at the end of step 5:

```
warning: unresolved symbol: ucd_lookup_category
warning: unresolved symbol: ucd_properties
warning: unresolved symbol: ucd_ispunct
warning: unresolved symbol: ucd_isupper
warning: unresolved symbol: ucd_tolower
warning: unresolved symbol: ucd_islower
warning: unresolved symbol: ucd_isspace
warning: unresolved symbol: ucd_isdigit
warning: unresolved symbol: ucd_isalpha
warning: unresolved symbol: ucd_toupper
warning: unresolved symbol: ucd_isalnum
```

and indeed the resulting JS files are not working properly, failing with 
errors citing missing ucd_* function(s).

I guess that it is a path/no compilation problem in the Makefile when 
run by emscripten --- I will investigate as possible.

AP

**Comment by pettarin** [comment]
@BenTalagan I have opened PR #248 which updates the directions to compile the JS worker.

Basically, the UCD tools should be compiled to JS with ``emscripten``, before compiling to JS the entire ``espeak-ng`` library (still with ``emscripten``).

For now, I have just added the relevant step to the directions to the ``emscripten/README`` file. The optimal solution, however, would be figuring out whether this intermediate step (compiling UCD tools to JS) can be done automatically, e.g. by modifying the top/root ``Makefile.am`` --- but I am not a make&friends expert, so for now I am happy with just knowing with an extra manual step.

**Comment by BenTalagan** [comment]
Hi @pettarin and many thanks for your time and patience !

I've tried to compiled from a checkout of your current repo, and it failed at step 5 (I had a few warnings before but they do not seem critical). 

```shell
Midgaard:emscripten ben$ emmake make
make: *** No rule to make target `../src/.libs/libespeak-ng.so', needed by `js/espeakng.worker.js'.  Stop.
```

This is the content of my ../src/.libs before step 5 :

```shell
Midgaard:.libs ben$ ls -lat
total 2992
drwxr-xr-x   7 ben  staff     238  1 mai 22:29 .
drwxr-xr-x  15 ben  staff     510  1 mai 22:14 ..
-rw-r--r--   1 ben  staff  749380  1 mai 22:14 libespeak-ng.1.dylib
-rw-r--r--   1 ben  staff  769016  1 mai 22:14 libespeak-ng.a
lrwxr-xr-x   1 ben  staff      20  1 mai 22:14 libespeak-ng.dylib -> libespeak-ng.1.dylib
lrwxr-xr-x   1 ben  staff      18  1 mai 22:14 libespeak-ng.la -> ../libespeak-ng.la
-rw-r--r--   1 ben  staff     954  1 mai 22:14 libespeak-ng.lai
```

**However**, creating the following link will allow to finish the build process :
```shell
ln -s libespeak-ng.a libespeak-ng.so
```
It seems to me a bit hacky, and maybe it's because there are some steps in the process which are not done the clean way? (That'd explain it is so complicated to emcompile on MacOS...).

**Comment by pettarin** [comment]
Hi, I forgot to mention that the new compilation flow (i.e., compiling 
UCD tools before the final target) has been tested on Linux, in the 
sense that eventually I get the worker and data JS files as expected on 
my laptop running Debian.

Yes, a few warnings are output, but you can safely ignore them. (Details 
below)

I am a bit confused about why you get the error in step 5, rather than 
in step 6 --- the latter I would understand better, since the 
emscripten/Makefile explicitly references

EM_LIBESPEAKNG_SO=../src/.libs/libespeak-ng.so

which seems to have .dylib extension on macOS. Probably the easiest 
approach is for me to check on my Mac Mini one of the next days.

BTW, always make sure you ``make clean`` or ``emmake make clean`` before 
the compilation --- I have wasted a lot of attempts due to emscripten 
failing to recognize that e.g. .o files were not LLVM IR files but 
actual object files from a previous compilation (with gcc, not with 
emscripten)...

AP


* About the warnings: two or three are generated by clang (but not by 
gcc), and I will report them separately, as they are relevant for 
espeak-ng per se. Then, there are warnings generated by emscripten when 
compiling UCD tests, and you can ignore them for sure. Finally, there is 
a warning about ieee80, generated by emscripten in the libespeak-ng.la 
pass, that I have not investigated yet. Anyway, the JS files are output 
(at least on Linux) and they work as expected, so I guess this latter 
warning can be safely ignored as well.

**Comment by BenTalagan** [comment]
> I am a bit confused about why you get the error in step 5, rather than
in step 6 --- the latter I would understand better, since the
emscripten/Makefile explicitly references

Sorry this is my mistake, you're totally right! I've probably messed up having multiple tabs opened (the step count has changed in your repo). My remarks about step 5 actually concern step 6.

> BTW, always make sure you ``make clean`` or ``emmake make clean`` before
the compilation --- I have wasted a lot of attempts due to emscripten
failing to recognize that e.g. .o files were not LLVM IR files but
actual object files from a previous compilation (with gcc, not with
emscripten)...

This is absolutely true, I get these kind of errors on .o files too on your step 5 for example (to get rid of them, a `emmake make clean` is necessary before `emmake make src/libespeak-ng.la`). The other warnings I get are at the end of `emmake make` phases on CCLD steps :

```shell
CCLD     src/libespeak-ng.la
WARNING:root:Dynamic libraries (.so, .dylib, .dll) are currently not supported by Emscripten. For build system emulation purposes, Emscripten will now generate a static library file (.bc) with the suffix '.dylib'. For best practices, please adapt your build system to directly generate a static LLVM bitcode library by setting the output suffix to '.bc.')
```

I believe your solution of updating the README is very acceptable atm, since it makes that issue non-blocking anymore (except that small dylib/so pb). Many thanks for your help, it is awesome!

**Comment by pettarin** [comment]
OK, no problem.

The fact that emscripten tries to be a "drop-in" replacement toolchain 
(i.e., compilation with clang -> LLVM IR -> JS instead of gcc -> native 
binary, driven by the same Makefile/configure) makes it prone to "real 
.o" vs "LLVM IR .o" issues.

This is especially true for eSpeak-ng, since to build the voice data one 
needs to do the full (native) compilation, and only then the emscripten 
compilation. I am afraid there is no real solution other than ``make 
clean`` or ``emmake make clean``.

With respect to the .so vs .dylib issue:

Ideally the "inner" emscripten/Makefile should be generated by the top 
./configure script, but these days I am a bit short on time to venture 
myself in this.

A quicker workaround might be testing for .so vs .dylib existence in the 
emscripten/Makefile, and act accordingly. I will give this second route 
a shot later this week. If not successful, I will just add a note for 
macOS users in the emscripten/README, warning them to manually add the 
symbolic link.

AP
