### ISSUE TITLE
Wrong phonetic transcription DE - Kuchen/Funken

### ISSUE THREAD

**Issue by hoenickf** [espeak-ng/espeak-ng#254]
Hi,
I discovered a bug in the phonetic transcription.
There are some words having a long u like: 
Kuchen, Husten, Buch.
 k-'U-x-@-n,  h-'U-s-t-@-n, b-'U-x

Others have a short u like: 
schulden druck.
S-'U-l-d-@-n,  d-r-'U-k

But espeak-ng pronounces every u like the same: 'U'

**Comment by valdisvi** [comment]
Currently eSpeakNG uses following flavors of **u** in German:

- 170 ms long [u](http://odo.lv/Espeak?eslang=-vde&speed=160&output=-w&debug=-x&text=%5B%5Bu%5D%5D.&formmethod=get)
- 240 ms long [u:](http://odo.lv/Espeak?eslang=-vde&speed=160&output=-w&debug=-x&text=[[u:]].&formmethod=get) both defined in [phsource/phonemes](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/phonemes) file, and
- 120 ms long [U](http://odo.lv/Espeak?eslang=-vde&speed=160&output=-w&debug=-x&text=%5B%5BU%5D%5D.&formmethod=get) defined in [ph_german](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_german) file.

Can you describe, how some of existing **u** or **u:** be used instead of **U** (or even other sound), and what should be decision (more or less general) rules for more proper sound?

(In eSpeakNG decision rules are described in [de_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/de_rules#L1173) file, more details of syntax is [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md).)

**Comment by hoenickf** [comment]
Its really hard to me to derive a general rule. 
Example which shows two very similar looking words with different "u":
should be like this:
Buchten (beach) -> U
buchte (money) -> u:
but its hard to find a general rule...

**Comment by valdisvi** [comment]
As these two words are very similar, can you write, how they are inflected (and/or some hyperlink with rules)?

**Comment by hoenickf** [comment]
I don't know how to write hyperlinks with rules. 
So I go for the inflection:

The first word is a noun.
Singular: Bucht (b U x t)
Plural: Buchten (b U x t @ n)

The second word is a verb
infinitive: buchen (b u: x @ n)
präsens (3th person singualr): bucht (b u: x t)
simple past (3th person singular): buchte (b u: x t @)
simple past (3th person plural): buchten (b u: x t @ n)

**Comment by valdisvi** [comment]
Because two forms of words overlap, they can't be separated just by looking on them. But we can use (probably because of that) capital letter of word to distinguish noun from verb.
For very frequent words we can use list of exclusions in ```de_list``` file, e.g. for listed words will mostly work:
```
buchen          b'u:x@n
bucht           b'u:xt
bucht           b'Uxt   $capital $verbf
buchte          b'u:xt@
buchten         b'u:xt@n
buchten         b'Uxt@n $capital $verbf
```
Will it be OK, to add these particular words as exceptions?
But for more general solution I registered new issue #266. If necessary, comment it about described problem and probable solution.

**Comment by hoenickf** [comment]
Okay thanks @valdisvi for your support!

**Comment by valdisvi** [comment]
@hoenickf I assumed, OK means listed words should be added as specific cases. As far as I understood, I added pronunciation for [Kuchen, Husten and Buch also](https://github.com/valdisvi/espeak-ng/commit/86b5411acfbfc74ca47df18f1543c711cd0ff8dd).

**Comment by hoenickf** [comment]
@valdisvi I reviewed your changes and can confirm its correct.
