### ISSUE TITLE
en : velarization of /n/ to /N/ before velar stops might have a too large scope

### ISSUE THREAD

**Issue by BenTalagan** [espeak-ng/espeak-ng#297]
Hello,

On this commit 6a85d3e63242411bbe5ef9b439805c43b07354d2 has been introduced the following phoneme rule for general english : 

```
phoneme n
  vcd alv nas
  ipa n
  IF nextPh(isVelar) THEN // /n/ is velarized to /N/ when before velar stops
    ChangePhoneme(N)
  ENDIF
  CALL base1/n
endphoneme
```

But isn't the scope of that rule a bit too large ? It would affect all english voices/accents/pronunciations on inter-word links such as 

`in Glasgow > ɪŋ ɡlˈazɡəʊ` 

but also affect the pronunciation of in- and un- prefixes. Cf : 

https://www.merriam-webster.com/dictionary/incoherent
https://www.merriam-webster.com/dictionary/uncouth

**Comment by rhdunn** [comment]
This is correct. It is intended to apply to things like the in- and un- prefices. Dictionaries (and other broad transcriptions) leave it out because /N/ is an allophone of /n/ (i.e. /n/ can be /N/ in some circumstances). This is like how stops like /p/ are aspirated at the start of a word (e.g. spot, pot), but that aspiration is not transcribed. Narrow transcriptions preserve these features.

English is a complex case because /N/ is an allophone (e.g. incoherent) and a phoneme (e.g. king). This is because in king and similar words, the /g/ is dropped (elided), but the /n/ is still velarized (i.e. /kIng/ => /kINg/ => /kIN/).

This change of /n/ to /N/ before /k/ and /g/ is a process called velar assimilation [2], [3], or velarization (assimilation affecting the velar place of articulation):

If you sound out words like incoherent and uncouth slowly, you will notice that when pronouncing the first /n/, the body of the tongue is touching the velar ridge (the large cavity behind the gum, before the tonsils) [1]. Here, the tongue is moving to the velar ridge to provide the stop part of the /k/ or /g/ sound, before the release part of those stops. If you compare this with words like intolerable and untied, the tip of the tongue touches the flat part of the gum behind the teeth, just before it moves upward (the alveolar ridge) [1].

If anything, it should only apply across words where there are no pauses (i.e. clause breaks).

[1] https://en.wikipedia.org/wiki/Place_of_articulation
[2] https://en.wikipedia.org/wiki/Assimilation_(phonology)
[3] http://martinweisser.org/courses/phonetics/connect/assimilation.html

**Comment by BenTalagan** [comment]
Hello Reece and thanks a lot for taking some of your time to answer in detail to this question!

Thanks also for highlighting the difference of approach between broad and narrow transcriptions ; that point of theory makes things much clearer for me concerning the motivations of phoneticians.

Though the velar assimilation process in that context is pretty clear to me, there are one or two points on which I'd like to humbly ask for some clarification. The degree of assimilation may vary a lot depending of the accent, dialect, or even the individual way of speaking of a locutor. This degree of assimilation is somewhat part of what constitutes a continuum between broad and narrow transcriptions, since a phonetical colour will happen to be rendered (or not) depending on where you place the cursor for the level of detail you want for the rendering. Of course, for a text to speech application such as espeak, the reasons for choosing a narrower transcription is perfectly understandable, even obvious. For a dictionary, I guess the motivations are not exactly the same (phonology, morphology, influence of the etymology & so on). 

In the way espeak is designed, all english prononciations are derived from a common prononciation which is "English_(Great_Britain)" ; this means that particular phonetic colors and details brought to this common trunk will be inherited by other prononciations (unless they are canceled by override in the derivate files). It seems a bit odd to me since I would have expected to have a more "neutral", broader form of english with less colors as the trunk (even if would be a bit artificial), from which the GB English prononciation would have derived just like the other ones, to avoid this inheritance (but maybe I'm wrong and it can be justified by some reality). 

On that specific point of velar assimilation, it seems to me (but I can be misleaded since I am not a native english speaker) that the degree of assimilation for certain specific prononciations such as the conservative RP which is very articulated (and somewhat 'perseverative') would be so low that choosing to render it with ŋ would tend to over-highlight it compared to reality.
  
This question of degree does puzzles me all the more that other assimilations that may exist in english are not rendered in espeak : for exemple, the labial assimilation of n in m before p and b (which is very common in french and appears in the orthograph itself) may also be present in english (cf espeak rendering of `input ˈɪnpʊt` and `inbox ˈɪnbɒks`, which could have been, as well, `ˈɪmpʊt` and `ˈɪmbɒks` ). So what is the reason behind these choices, is it really a question of quantity and cursor, as I suspect ?

Thanks!

Ben

**Comment by rhdunn** [comment]
Regarding the pronunciations, they are derived as an extension of John Wells' Lexical Sets (see https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages/gmw/en.md). These are sometimes customised specifically for different accents (e.g. American variants of words like vase and antibody) -- which is why you will see things like `?3` and `?!5` for various rules and words. I want to make this configuration more flexible as documented in #286 to allow for different accent configurations. The specific rendering of those phonemes then varies across the different English accents.

My understanding of velar assimilation of /n/ before /k/ and /g/ (specifically within a word) is that it is universal in English accents -- unless you have a specific case where this is not true. Dictionaries are an unreliable source as they can and do omit phonological features (like aspiration of /p/, and other stops at the start of a word/syllable). __NOTE 1:__ There is variation of -ng words (ringer as /rINg3/ or /rIN3/), and -ing (e.g. adding as /adINg/, /adIN/ or /adIn/ -- note that the latter is due to the lack of the /g/ influencing the velarization of /n/). __NOTE 2:__ It is difficult to pronounce the /n/ without velarization when the /n/ is followed by /k/ or /g/, compared with the other examples on that page (with the exception of apprenticeship, where the /sS/ is also difficult to pronounce). The -in' variant of -ing is easy because in that case the /g/ sound is not pronounced.

I agree that the other features vary with accent, formality (whether or not you are carefully enunciating the words) and how fast you are speaking. I have not looked into these yet and where best to apply them.
