### ISSUE TITLE
Add a custom voice

### ISSUE THREAD

**Issue by life-coder** [espeak-ng/espeak-ng#316]
Hi,

is it possible to add custom voices? Our own for example?

Best regards

**Comment by SadaleNet** [comment]
I'm also interested in doing that. It seems to be possible, but rather difficult. And I haven't tried out this idea.

The [espeakedit](http://espeak.sourceforge.net/editor.html) program can be used to edit to vowel/diphones. To add custom voice, I'd first record the sound of all vowels and diphones of a language. Then use the program to find the formants of the vowel/diphones.

Since espeak is using sinusoidal synthesis algorithm (See [list of popular speech synth algorithm](http://research.spa.aalto.fi/publications/theses/lemmetty_mst/chap5.html)), the algorithm cannot synthesize most type consonants well (except the nasals one). So you'd also need to prepare sound sample for each of those consonants, in .wav format IIRC. It'll be concated to the vowel by espeak.

I'm no way being a professional on espeak. It's just the case that I'm also interested in doing something similar. And that's my finding on this topic after extensive research on it. Please do notify me or post something here when you managed to do that. I'd like to check if this idea is feasible and the quality of the result. Thank you very much! :)

**Comment by Christianlm** [comment]
Hi,
I'm interested to generate better formants for italian vowels.
I'm searching a good solutions and time ago I find this old thread:

https://sourceforge.net/p/espeak/discussion/538921/thread/48541c99/?limit=25#96d4/4271

My problem is that I'm working only in Windows and I can't use the modified Praa to write spectrum.dat file for espeak.

Cheers.

**Comment by SadaleNet** [comment]
I'm sure that it's possible to compile Praat on Windows. But it may take a lot of Google-fu.

How about using a virtual linux machine or enabling [linux subsystem on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) if you're on Windows 10?

**Comment by YousafKhan1** [comment]
Hi I would like to add custom files how i can do it in windows
