### ISSUE TITLE
A bug in Arabic espeak

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#324]
Hi!
I don't know, if this is good, but maybe not. This arabic letter م is pronounced, as meetar, but It must be pronounced, as meem. Is It misstake?
I think, that meetar is arabic word for metter, but I am not shure, if this is only in NVDA, or no. I think on this bug. Please, could You on this misstake?
Because letter 'm' is pronounced normally, as 'm' not as 'metter'.
Thank You.
Marco

**Comment by valdisvi** [comment]
That was because of unnecessary rule to spell it as meter.

**Comment by valdisvi** [comment]
If you are curious, you can check any other single letters, which can be misspelled in some contexts [here](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/ar_list#L248)
My experience for English and Latvian shows, that only uniquely appearing units, which cannot appear in other context can be set to be spelled in unit name (i.e. almost never).

**Comment by linuxscout** [comment]
How can add a rule to pronounce the meter unit 'م' instead of single  letter Meem?

**Comment by valdisvi** [comment]
There is no reliable way to point out when m is used as a measure, because:

* Main reason is that eSpeakNG converts numbers to words internally before other processing,
* One can write units in many different (often inconsistent) ways: "1m", "1 m", and "1.m" for "first meter" or "1. m" (the same with space etc).

Users of Latvian community required me to make spelling as consistent and predictable as possible, therefore most of initially added abbreviations were dropped, and anybody who uses eSpeakNG frequently know, what e.g. "one em" means.

**Comment by linuxscout** [comment]
If it's the case, we must change all single letters units to be pronounced as ordinary letters
dictsource/ar_list

م		mitar
س		su?aal
ج		dZawaab	
ص s[afHah

As an arabic speaker and developer I think that valdisvi proposed solution is good, except for Waw, 
because generally the Waw letter means "and" and can pronounced as "wa" instead of the letter name.

I propose to remove the above rules and close the issue.

**Comment by rhdunn** [comment]
Issues should not be closed until the fix has been merged into the master branch. Doing otherwise makes it difficult to track the state of issues.

eSpeak converting numbers to words internally is not a problem -- it classifies the context before the word conversion, so it can handle cases like "1st".

Handling of unit-based abbreviations (meters, seconds, pounds, ounces, etc.) are not currently supported in eSpeak for any language. Issue #115 was raised to track adding that feature.

**Comment by valdisvi** [comment]
I commented out mentioned letters in another commit.
