### ISSUE TITLE
eSpeak-ng 1.49.2: Chinese Cantonese dictionary (zhy_dict) problem

### ISSUE THREAD

**Issue by surfer0627** [espeak-ng/espeak-ng#338]
Hi,
One issue occured, when user use eSpeak with screen reader NVDA. NVDA reports number when the Chinese character is encountered by espeak
Example: 鋼1鐵3人4馬3斯1克4：從2特4斯1拉1到4太4空1探4索3，大4夢4想3家1如2何2創4造4驚1奇2的5未4來2
Expected: 鋼鐵人馬斯克：從特斯拉到太空探索，大夢想家如何創造驚奇的未來

Could someone help to check Chinese Cantonese dictionary (zhy_dict)?
Thanks.

related issue on NVDA GitHub:
[#7787](https://github.com/nvaccess/nvda/issues/7787).

**Comment by valdisvi** [comment]
Issue #335 could be related to this issue.

**Comment by valdisvi** [comment]
It is strange, that issue is only for Mandarin Chinese:

```
espeak-ng -X -vcmn "铁人麝香：从特斯拉到太空探索"
Translate '铁人麝香'
Replace: 铁   tie3 
Translate 'tie3'
  1	t        [th]

  1	i        [i]
 22	ie       [iE]

Found: '_3' [san55]  
Replace: 人   ren2 
Translate 'ren2'
  1	r        [z.]

  1	e        [o-]

  1	n        [n]

Found: '_2' [@r51]  
Replace: 麝   she4 
Translate 'she4'
  1	s        [s]
 42	sh (+    [s.]

  1	e        [o-]

Found: '_4' [si[51]  
Replace: 香   xiang1 
Translate 'xiang1'
  1	x        [S;]

  1	i        [i]
 22	ia       [iA]

  1	n        [n]
 42	ng (K    [N]

Found: '_1' [ji55]  
 th'iEsa55n_| z.'o-n@r51_| s.'o-si[51_| S;'iANji55_|
Translate '从特斯拉到太空探索'
Replace: 从   cong2 
Translate 'cong2'
  1	c        [tsh]

  1	o        [o]
 63	ong (K   [ong]

Found: '_2' [@r51]  
Replace: 特   te4 
Translate 'te4'
  1	t        [th]

 22	t) e     [@]
  1	e        [o-]

Found: '_4' [si[51]  
Replace: 斯   si1 
Translate 'si1'
  1	s        [s]

  1	i        [i]
 22	s) i     [i[]

Found: '_1' [ji55]  
Replace: 拉   la1 
Translate 'la1'
  1	l        [l]

  1	a        [A]

Found: '_1' [ji55]  
Replace: 到   dao4 
Translate 'dao4'
  1	d        [t]

  1	a        [A]
 22	ao       [Au]

Found: '_4' [si[51]  
Replace: 太   tai4 
Translate 'tai4'
  1	t        [th]

  1	a        [A]
 22	ai       [ai]

Found: '_4' [si[51]  
Replace: 空   kong1 
Translate 'kong1'
  1	k        [kh]

  1	o        [o]
 63	ong (K   [ong]

Found: '_1' [ji55]  
Replace: 探   tan4 
Translate 'tan4'
  1	t        [th]

  1	a        [A]

  1	n        [n]

Found: '_4' [si[51]  
Replace: 索   suo3 
Translate 'suo3'
  1	s        [s]

  1	u        [u]
 22	uo       [uo]

Found: '_3' [san55]  
 tsh'ong@r51_| th'@si[51_| s'i[ji55_| l'Aji55_| t'Ausi[51_| th'aisi[51_| kh'ongji55_| th'Ansi[51_| s'uosa55n_|
```
But it works properly for Cantonese Chinese:
```
espeak-ng -X -vyue "铁人麝香：从特斯拉到太空探索"
Found: '铁' [tit3]  
Found: '人' [jan4]  
Found: '麝' [se6]  
Found: '香' [hoeng1]  
 t'i3t_| j'a4n_| s'e6_| h'oeng1_|
Found: '从' [cung4]  
Found: '特' [dak6]  
Found: '斯' [si1]  
Found: '拉' [laai1]  
Found: '到' [dou3]  
Found: '太' [taai3]  
Found: '空' [hung1]  
Found: '探' [taam3]  
Found: '索' [sok3]  
 c'ung4_| d'a6k_| s'i1_| l'aai1_| d'ou3_| t'aai3_| h'ung1_| t'aa3m_| s'o3k_|
```
Maybe by comparing configuration files for:
* Mandarin Chinese [zh_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/zh_list) and [zh_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/zh_rules) and
* Cantonese Chinese [zhy_list](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/extra/zhy_list) and [zhy_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/zhy_rules)

and some additional tests (e.g. in [test webpage](http://odo.lv/Espeak), if you don't have better options) you can narrow down, what is important difference?

I noted some differences, which are NOT causes of this issue:
* Applied rules for Mandarin are much longer (but I couldn't prove it could be related to issue yet)
* `zhy_rules` doesn't have **.replace** group of rules (but I tried to comment out **.rules** section for `zh_rules` file but it didn't change anything)
* `zhy_list` is symbolic link to `dictsource/extra/zhy_list` file (but making copy of it in `dictsource` folder didn't change anything)

**Comment by valdisvi** [comment]
surfer0627, I have pushed fix to [my repository](https://github.com/valdisvi/espeak-ng/commit/60e9e3ebcbb6c5d77f5ddb4bc1f3bee61abe1b6e). You can test it online [here](http://odo.lv/Espeak).

**Comment by surfer0627** [comment]
Hi @valdisvi and @rhdunn, thank you for all of your assistance. Acctually, I do not know how to test it online without using NVDA. I'll find someone help.
Another thing is that this reading case occur in Chinese Mandarin, not Chinese Cantonese. Sorry, I quote message and make mistake.

**Comment by surfer0627** [comment]
Hi @valdisvi,
After testing, this issue has been resolved. Thanks a lot.
