### ISSUE TITLE
Wav file check fails when pulseaudio for pcaudiolib is enabled

### ISSUE THREAD

**Issue by valdisvi** [espeak-ng/espeak-ng#372]
This is new issue found after issue #278 was solved.
When [pcaudiolib](https://github.com/espeak-ng/pcaudiolib) is compiled with switch `--with-pulseaudio=yes` then `make check` fails when checking binary output  of wav files:
Output shows:
```
  TEST      tests/languages.test
/usr/bin/sha1sum
testing de
testing en
testing en-029
testing en-GB-scotland
testing en-GB-x-gbclan
testing en-GB-x-gbcwmd
testing en-GB-x-rp
testing en-US
testing ja
testing bg (English text)
1c1
< ad98e816727288c7f3c525a4b4c30e72c7ea0c00
---
> 2be95f9eb3cbba5a711de2106e244755b6b23cba
Makefile:2423: recipe for target 'tests/languages.check' failed
make: *** [tests/languages.check] Error 1
```
Other wav file tests after first one fails also, just they are not shown because of first fail.
Probably some condition should be added for these checks.

**Comment by rhdunn** [comment]
I wonder if that's because espeak is outputting something to stdout/stderr and interfering with the audio output. The tests are passing for me locally, so I can't easily investigate.

As an aside, I am using similar hashing to test and compare changes to all voices using:

    ESPEAK_DATA_PATH=`pwd` src/espeak-ng -v "$VNAME" --stdout "$MESSAGE" 2>/dev/null | sha1sum

and am seeing occasional variation in some of the MBROLA voices. I haven't figured out why that is the case yet.

**Comment by valdisvi** [comment]
File with pulse it starts similarly, but then it gets slower and with longer silence:
![att02](https://user-images.githubusercontent.com/1501944/34844020-c6c1c7d4-f718-11e7-8319-bfa5b93eeca9.png)
And  how it  looks with `vbindiff`:
![att03](https://user-images.githubusercontent.com/1501944/34844102-0c7a0caa-f719-11e7-8759-b010b1ad0167.png)
And following are actual output wav files:
[out-alsa.wav.zip](https://github.com/espeak-ng/espeak-ng/files/1623909/out-alsa.wav.zip)
[out-pulse.wav.zip](https://github.com/espeak-ng/espeak-ng/files/1623910/out-pulse.wav.zip)
sha1sums:
```
ad98e816727288c7f3c525a4b4c30e72c7ea0c00  out-alsa.wav
2be95f9eb3cbba5a711de2106e244755b6b23cba  out-pulse.wav
```

**Comment by valdisvi** [comment]
As it is reproducible, maybe workaround would be checking with one or another sha1sum?

**Comment by rhdunn** [comment]
The problem then is if there are more variations. I seem to recall there being a "flutter" setting in espeak to vary the output slightly, but that would have a more noticeable effect. Also, it should not make a difference what audio is enabled, because the audio data is being written to stdout, not to the audio device, and the resulting wav output is not lossy, so there should not be any encoding differences.

Another thing it could be is that espeak writes its audio to an echo buffer, before mixing it into the output buffer. It does this because it sounded objectively better to Jonathan. Ideally, that kind of thing should be configurable, but that would be something to look at in a future version. It may be that one of those buffers can sometimes get data it shouldn't, and that is causing the output to be slightly different. Something like that would be difficult to identify.

**Comment by valdisvi** [comment]
After reorganization of tests f4ff5c6802abcb28e4225afcec91e35a851f9f98 and checking produced wav just for [language phonemes](https://github.com/espeak-ng/espeak-ng/blob/master/tests/language-phonemes.test) problem has disappeared.
