### ISSUE TITLE
German "V#" phoneme sounds wrong at a fast speed

### ISSUE THREAD

**Issue by hozosch** [espeak-ng/espeak-ng#389]
Hi,
I have made some improvements to the german espeak, as you may know. A few days ago it was included in nvda. I've actually been told that it sounds bad from a user who I know he uses espeak at a very fast speed, the fastest you can get without sonic. I tried setting it to that speed, and I confirm that the "V#" (r after a vowel) sounds a bit strange with a speed as fast as that. I don't know if there's a solution to improve that, but I would be glad if you could have a look into that and, if you have found a solution, implement it as fast as possible, because it would be bad to include this in a stable release of NVDA as it is now.

**Comment by rhdunn** [comment]
I have reverted the changes due to feedback, so this is no longer relevant. Additionally, it was hard to tell which changes had what effect on the pronunciation. It would be helpful to split the fixes into different related chunks (e.g. pronunciation corrections, new phoneme and associated pronunciation changes, changes to the `r` sound, etc.).
