### ISSUE TITLE
Issue with latest ESpeak in Serbian

### ISSUE THREAD

**Issue by nidza07** [espeak-ng/espeak-ng#520]
### Steps to reproduce
Read the following word, written in standard English alphabet with ESpeak set to Serbian:
Test.
Now read this same word, written in Serbian cyrillic alphabet:
тест
### Expected behaviour
Both words should be pronounced the same way
### Actual behaviour
The cyrillic word is read letter by letter, as if it was written like t e s t. This happens with everything written in cyrillic.
### Version used
eSpeak NG version 1.49.3 de

**Comment by michaelDCurran** [comment]
With espeak language set to Serbian:


"тест":

t'@ 'E s'@ t'@


"Test":
t'Est

Mick

**Comment by jaacoppi** [comment]
This is because serbian currently doesn't have rules for cyrillic letters, only latin. 

Is it okay to use the alphabet listed here: https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet

I can add the support next week.

**Comment by nidza07** [comment]
Yeah, that alphabet is fine.

**Comment by rhdunn** [comment]
I can reproduce the issue -- it works in 1.49.2, but not 1.49.3~32ab396e. I'm preforming a bisect on the code now.

**Comment by rhdunn** [comment]
This issue is caused by commit 9f0667de8651fe646b3b3f3a498f74d6d71adcab. That change added support for more flexible `.replace` rules, allowing multiple characters to be replaced by multiple other characters. This changed the way replace rules are represented in the dictionary file format.

The Bosnian, Croatian, Serbian, and Slovenian languages use a Cyrillic to Latin character mapping that is set within the code instead of via `.replace` rules in the language files. That mapping was not updated to the new format, so it no longer works.

Specifically, in `tr_languages.c`, the hr, bs, sl, and sr languages set `tr->langopts.replace_chars` to `replace_cyrillic_latin` which is in the old format.

The proper way to fix this is to add `.replace` rules to those files mapping Cyrillic to Latin and remove the `replace_cyrillic_latin` variable. While this will duplicate the mapping tables, it should be easier to read, is consistent with other languages (Greek, Japanese, etc.) and can be adjusted as needed for language-specific differences.

**Comment by zstanecic** [comment]
no reece, i should'nt create the separate issue, as it is the same south slavic language branch.
unfortunatelly it can be reproduced with NVDA only, but not in the odo.lv page.
please install NVDA, and reproduce it yourself.
and compare with 1.49.2

**Comment by rhdunn** [comment]
The macedonian language does not exhibit the bug described in this issue:
```
$ src/espeak-ng -xv mk тест
 t'est
```

It does not matter if it is the same language branch, it is a different bug.

**Comment by michaelDCurran** [comment]
@zstanecic: Please either create an espeak-ng issue as Reece has asked, 
or if you believe the issue only shows up in NVDA, then please create an 
NVDA issue.

Either way, without an issue we cannot investigate further.

**Comment by rhdunn** [comment]
I have converted the `replace_cyrillic_latin` table to `.replace` rules with tests. There are still a few issues, as some of the characters are getting replaced by the wrong characters, so this issue is not fully fixed.

@valdisvi Can you take a look at these? Thanks.

**Comment by rhdunn** [comment]
NOTE: I have also removed the mapping for Slovenian, as the only references to using Cyrillic is in alphabets from 1824-1838 with minimal usage. Those alphabets don't follow the modern mapping, so would need custom replacement rules if they were to be supported.

**Comment by rhdunn** [comment]
This specific issue (missing `.replace` rules) has now been fixed. The remaining issues are covered by #523.
