### ISSUE TITLE
Ukrainian Support

### ISSUE THREAD

**Issue by MissValeska** [espeak-ng/espeak-ng#546]
Hello, I am working with tensor flow to train a neural network on Ukrainian text and audio. To do so, I need Aeneas, which needs espeak or espeak-ng (or others), however, none of these TTS engines support Ukrainian, only Russian, which I fear won't be sufficient.

Are there any plans to add Ukrainian support to espeak-ng? I am considering following the available tutorials to add some rudimentary Ukrainian support, but since accents aren't the same as Russian, while still being random, I'm concerned I'd need to compile a different dictionary, and I'm not sure how to do that. Further, I'm curious if anyone could explain to me what espeak-ng does in the context of Aeneas, as I'm wondering if using the Russian dictionary, which wouldn't be perfectly accurate, would still work. If every word has to be perfect, accent included, then a Ukrainian dictionary file would be necessary, otherwise it simply wouldn't work, would it not?

Thank you so much!

**Comment by valdisvi** [comment]
Adding new language is described [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md), to test it practically, you need to set up [your own](https://github.com/espeak-ng/espeak-ng#linux-mac-bsd) development environment, or, you can use [hosted solution](https://odo.lv/EspeakGuide).

It is unclear, what you are planning to do with trained engine. 
* If you want to use it as a text-to-speech engine, then training tensorflow to talk like espeak-ng seems strange, because then tensorflow will work as (probably more exciting, but bad and overcomplicated) actor of espeak-ng, inheriting all of espeak-ng's deficiencies (incorrect intonation, mechanical sound etc.)
* If you want to use it as speech-to-text engine, then hoping that training it with mechanical voice will allow recognition of human speech is (in my opinion) very toptimistic, considering faults of neural networks (e.g. for [pictures](https://arxiv.org/abs/1412.1897) and for [sound](https://arxiv.org/abs/1801.01944)).

espeak-ng is text-to-speech engine, which produces sound (in audio system, standard output or *.wav file) from passed text (given from standard input, passed parameters or text file). If you want to prepare existing set of text and sound files to train tensorflow, you can use e.g. [Aeneas](https://www.readbeyond.it/aeneas/).

**Comment by MissValeska** [comment]
Well, I would like Ukrainian support regardless, however, I need it because
I'm following this guide
https://medium.com/@klintcho/creating-an-open-speech-recognition-dataset-for-almost-any-language-c532fb2bc0cf

But for Ukrainian.

**Comment by rhdunn** [comment]
Hi,

> Hello, I am working with tensor flow to train a neural network on Ukrainian text and audio. To do so, I need Aeneas, which needs espeak or espeak-ng (or others), however, none of these TTS engines support Ukrainian, only Russian, which I fear won't be sufficient.
>
> Are there any plans to add Ukrainian support to espeak-ng?

There are no specific plans to add Ukranian support. However, if someone wants to add support for the language, they are welcome to do so.

> I am considering following the available tutorials to add some rudimentary Ukrainian support, but since accents aren't the same as Russian, while still being random, I'm concerned I'd need to compile a different dictionary, and I'm not sure how to do that.

An eSpeak language is made up of 5 parts: the phoneme table (describing the phonemes in the language, and how to synthesize them), the dictionary rules (grapheme to phoneme mapping), and dictionary list (pronunciation of word exceptions, numbers, letters, etc.), a language file associating these together, and some setup in the `tr_languages.c` source file. There is some documentation on this in the docs folder, and the existing languages can be used as a reference.

Let us know if you have any specific questions regarding adding Ukranian support.

> Further, I'm curious if anyone could explain to me what espeak-ng does in the context of Aeneas,

From https://www.readbeyond.it/aeneas/docs/libtutorial.html#concepts: "The aeneas.ttswrappers package contains the wrappers for several built-in TTS engines which can be used in the synthesis step of the alignment procedure."

Therefore, it is using eSpeak (or some other TTS engine) when matching up the text to the audio being annotated.

> as I'm wondering if using the Russian dictionary, which wouldn't be perfectly accurate, would still work. If every word has to be perfect, accent included, then a Ukrainian dictionary file would be necessary, otherwise it simply wouldn't work, would it not?

I suspect that using the Russian language may work for your purpose, as Aeneas only needs to match the clause end, and not individual words or phonemes. This would be like using it on audio in a different English/French/Spanish/etc. accent, or with words the TTS does not handle correctly.

**Comment by MissValeska** [comment]
Thank you, that's extremely interesting. So even with simply using the
existing Russian language with the Russian language dictionary, it should
still work? Or should I still add the required Ukrainian language files but
use the Russian dictionary?

**Comment by waSRull** [comment]
I also wanted to convert ukrainian speach to audio.
@MissValeska,  have you built ukrainian lang dict?

**Comment by valdisvi** [comment]
@MissValeska, I have added initial support for Ukrainian language. You can test it [online](https://odo.lv/Espeak) and improve it yourself by following [contributor guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md).
