### ISSUE TITLE
espeak-ng --compile-debug=xx returns "Can't access (r) file 'xx_rules'"

### ISSUE THREAD

**Issue by ValdisVitolins** [espeak-ng/espeak-ng#57]
When trying to compile language with advanced debugging
e.g. from `src` map (and similarly from different other maps):

    ./espeak-ng --compile-debug=lv
It returns:

    Can't access (r) file 'lv_rules'

**Comment by rhdunn** [comment]
When running the `--compile`/`--compile-debug` commands, you need to run:

    cd dictsource
    ESPEAK_DATA_PATH=`pwd`/.. ../src/espeak-ng --compile=lv
    ESPEAK_DATA_PATH=`pwd`/.. ../src/espeak-ng --compile-debug=lv

I have tested these on my system and they both work. Running them from the top-level source directory (using the current code), I get:

    $ ESPEAK_DATA_PATH=`pwd`/.. src/espeak-ng --compile-debug=lv
    Error processing file 'lv_rules': No such file or directory.

I'm getting a different error message because I have recently improved the error handling to provide better information on the problem.

**Comment by ValdisVitolins** [comment]
Thanks!
I've done this in following way:
cd to espeak-ng project root folder, then:

    cd dictsource/
    ../src/espeak-ng --compile-debug=lv
