### ISSUE TITLE
Adding Tagalog /Filipino language to Espeak

### ISSUE THREAD

**Issue by Giovani93** [espeak-ng/espeak-ng#581]
Hello.
Here is Marco from Slovakia.
I have one idea to You. Ofcourse, I am not speaker of this language, but please, can You add Tagalog/Filipino language to Espeak?
I use Espeak NG with NVDA to learn new languages, because I am blind and It'll be maybe good idea to do It.
Thank You.
best regards
Marco Oros

**Comment by valdisvi** [comment]
Espeak may not be the best tool to learn spoken language, because of different (and not always great) quality of pronunciation for it. If we would add basic support for Tagalog/Filipino, pronunciation quality would be very low and would not be usable for learning.
I suggest [https://www.101languages.net/](https://www.101languages.net/) web site, e.g. this for [Tagalog](https://www.101languages.net/tagalog/) as a start.

**Comment by gr01d** [comment]
Hi, I speak native Filiino/Tagalog. How can I contribute to this project? I also need espeak to speak tagalog language for my project too.

**Comment by valdisvi** [comment]
Look at [Steps for contribution to set up eSpeak NG project](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md#steps-for-your-contribution) and then [Adding or Improving a Language](https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md) particularly.
