### ISSUE TITLE
Questions about espeak-ng

### ISSUE THREAD

**Issue by Nokia808** [espeak-ng/espeak-ng#641]
Hi. I'm Fedora 30 X 64 bit Cinnamon edition users. I'm very beginner with TTS engine on Linux though I'm now about near 4 years Linuxer. 

I have difficulties with espeak-ng ......

1) is ther a GUI available for configuration of espeak-ng ? This can solve great deal of problem.

2) currently the voice is of low quality & I like to change voice. In /usr/share/espeak-ng-data/voices there are 2 folders: mb & !v
I think that mb is voices while !v is for variants, isn't it ?
How can I change default voice to what I prefer ? I used "espeak-ng --voices" to list available voices, then I tried "espeak-ng -v<voicename> <text>" to test voices. But how can I change default one.

3) it seem that all installed voices on my Fedora are of low quality. I'm not sure they are such or they just need to correct their parameters ?

4) if all voices of same quality & can not improved by changing their parameters, then where can I get high quality voices to be used with espeak-ng ?

**Comment by hotlittlewhitedog** [comment]
Yop @Nokia808 , what do you mean by low quality?  
I have the same question about how to change the configuration to have a voice less robotic.

**Comment by Punkroku** [comment]
hmm... I am assuming you use the linux version:

have you tried espeak --help or espeak-ng help 
also you can try this alias tts="espeak-ng" && tts --help
Then you will learn the options to adjust pitch and speed in espeak its -p and -s arguments to change the voice you have to select the voice using something like:
espeak-ng -v pl "braterska"

see the list of voices by typing:
espeak --voices
I dont know how to change the default voice but you could alias it like:
alias espeak="espeak -v jp"
or whatever voice you choose

**Comment by valdisvi** [comment]
1. espeak-ng works only as a command line application. Adding GUI to that will just [hide things and add clutter](https://faculty.georgetown.edu/irvinem/theory/Stephenson-CommandLine-1999.pdf).
2. Default voice/language for espeak-ng is `en` which is short-hand of `en-gb`. You have to pass value for `-v` parameter e.g. `-v en-us` to use different voice/language. `espeak-ng --voices` command shows only natively synthesized voices. You can get list of MBROLA voices [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md#voice-names).
3. Most of MBROLA voices are created with 16kHz sampling frequency. So, theoretical limit is 8kHz, but practically it is even lower than that (~4hHz). If there are several versions of MBROLA voices available for language, one with bigger number usually has better quality. You can only adjust [phoneme translation](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md#2-add-mbrola-phoneme-translation-file) with parameters.
4. You can create your own MBROLA voice by recording samples, cutting diphones from them and converting samples with [MBROLATOR](https://github.com/numediart/MBROLATOR) into MBROLA database. It requires at least several months for single person to get something usable and probably more than year to get better sound than for existing voices.

**Comment by Punkroku** [comment]
Sorry to barge in the topic w/ tangent->
I had a project tiny.cc/scribblegame that needs a GUI like Gimp TOOL KIT. I have no idea how to wrap the BASH i figure I can use sed for placement of icons for the game.
I tried asking on those STACK websites and my questions were all deleted so I wasted my time and could not get rep. I tried posting copies of my questions on github.

___ END

I am looking for an attorney for Slander, Freedom of Speech in court, and Appeal Fraud.

PUBLIC NOTICE:
In re: CAPPELLO Vs PEOPLE
NOTICE OF APPEAL FRAUD CLAIM; Let it be known that CAP[P]ELLO is not against
nor versus the people in any way shape form or mannerism, nor is
CAPPELLO falsely represented in the matter like the People who are
falsely represented by 1 District Attorney Representative acting in a
conflict of interest. CAP[P]ELLO makes a claim of appeal fraud in case
SCD223160 and is looking for an attorney for Slander of "Mentally
Incompetent." CAPPELLO is aware that freedom of speech is denied in
court on a daily basis. CAPPELLO would like public court/jury via
youtube or other outlet such as written communication with fingerprints
and partys of all side known and identities verified instead of
concealment of documentary record in violation of CA PENAL CODE 135.

It seems that my emails get "lost" you can snail mail me at the address
below and I will reply with sticker gifts.(tiny.cc/oisticker)
Ember AR Leona
250 S. Lyon Ave Ste E 108
Hemet, CA 92543
It seems that my emails get "lost" you can snail mail me at the address below and I will reply with sticker gifts.(tiny.cc/oisticker)
Ember AR Leona
250 S. Lyon Ave Ste E 108
Hemet, CA 92543

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
火曜日, 八月 27, 2019 1:19 午後に、Valdis Vitolins <notifications@github.com>は書きました：

**Comment by valdisvi** [comment]
Easiest way to wrap Bash into GUI is using [Zenity](https://en.wikipedia.org/wiki/Zenity).

**Comment by Derphotdog** [comment]
was there any update on if there was a way to change the default voice?
