### ISSUE TITLE
a very basic question 

### ISSUE THREAD

**Issue by FRANKLINSHEPS** [espeak-ng/espeak-ng#654]

**Comment by FRANKLINSHEPS** [comment]
I am new to github and that is probably the issue 
I understand it is a command line interface in dos windows etc
I downloaded  espeak-ng-master.zip in order to at the dos command line run the program to read a text file into a wave file   I expected  for example   espeak-ng.exe  test.txt  test.wav  
I cannot find the exe file which I presume would be espeak-ng.exe to which I attach the command parameters
my zip contains a ton of other things that I don't know what they are but no exe's or even dll's
I am sure I am just dumb but your help would be appreciated 
did I download the wrong thing ??

**Comment by FRANKLINSHEPS** [comment]
I am so new I dont  even know how to post !

**Comment by The1Freeman** [comment]
https://github.com/espeak-ng/espeak-ng/releases
Check the releases tab

**Comment by ryandesign** [comment]
@FRANKLINSHEPS, what you've downloaded there is the source code. At the Releases page mentioned in the preceding comment, you can instead download installers for Windows that will install pre-built executables, which is probably what you're looking for.

This issue should be closed since the question has been answered.
