### ISSUE TITLE
fr voice garbles copyright sign

### ISSUE THREAD

**Issue by npitre** [espeak-ng/espeak-ng#657]
Just listen to:

`espeak-ng -v fr "* © 2019 Bla"`

**Comment by valdisvi** [comment]
Simple workaround for this is commenting out `©	symbole Copyright` line in [fr_emoji](https://github.com/espeak-ng/espeak-ng/blob/1fa6d52a918f3e574240a32ba75092c350e9c5ef/dictsource/fr_emoji#L27) file, especially because that is also defined in [fr_list](©	_^_en) file and will be used if there is no entry in `fr_emoji` file.
Understanding why `©	symbole Copyright` breaks pronunciation rules and fixing it in more general way needs much more investigation.

**Comment by npitre** [comment]
If that may give more clue, running `espeak -X -v fr "© ba bla baba"` 
produces `sE~b'Ol(base) @@ @@@ @@@@`.

**Comment by rhdunn** [comment]
The symbols should preferably be defined in the _emoji files and not the _list files, as they will then be consistent with the other emoji files and translated/updated whenever Unicode updates the translation.

I get the following output:

    $ src/espeak-ng -xv fr "* © 2019 Bla"
    aster'isk: sE~b'Ol(base) k: @@@ @@@ @@@@@@ @@@

    $ src/espeak-ng -Xv fr "* symbole Copyright 2019 Bla"
    aster'isk: sE~b'Ol (en)k'0pIr,aIt(fr) dY mil dizn'Wf bl'a

It looks like there is an issue switching languages when expanding symbols with text, as it is trying to resolve to the `base` phoneme table and not `en` for some reason.
