### ISSUE TITLE
problem with the testing languages

### ISSUE THREAD

**Issue by tc-dl** [espeak-ng/espeak-ng#662]
cloned espeak-ng on ubuntu 18.04.3 for testing and refinement of the Bashkir language. 
after installing all the required libraries, perform the following commands: 
./autogen.sh 
./configure --prefix=/usr 
make 
sudo make LIBDIR=/usr/lib/x86_64-linux-gnu install 
if you check any language the espeak command-ng -v ru --stdout "Hello!" | paplay gives: 
symbol lookup error: espeak-ng: undefined symbol: espeak_ng_SetVoiceByFile failed to open the audio file. 
what could be the problem?

**Comment by valdisvi** [comment]
Because espeak-ng cannot find language files, I suspect `LIBDIR` is set incorrectly.
I compile just with `sudo make install`. If you have to use paplay, then you probably have not compiled espeak-ng with [pcaudiolib](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md#linux-mac-bsd) support. Check that after 
```
./configure --prefix=/usr`
```
you see
```
...
PCAudioLib:                    yes
...
```
For latest *ubuntu systems you cant install precompiled package, therefore you have to get,  compile and install it [from source](https://github.com/espeak-ng/pcaudiolib).

**Comment by tc-dl** [comment]
I checked, PCAudioLib: yes.
For latest *ubuntu systems you cant install precompiled package, therefore you have to get, compile and install it from source. maybe this is the problem? there may be more that can not correctly do.

**Comment by valdisvi** [comment]
Check that libraries are actually installed:
```
ldconfig -p|egrep "espeak|pcaudio"
```
should show something like this:
```
	libpcaudio.so.0 (libc6,x86-64) => /usr/lib/libpcaudio.so.0
	libpcaudio.so (libc6,x86-64) => /usr/lib/libpcaudio.so
	libespeak-ng.so.1 (libc6,x86-64) => /usr/lib/libespeak-ng.so.1
	libespeak-ng.so (libc6,x86-64) => /usr/lib/libespeak-ng.so
```

**Comment by tc-dl** [comment]
checked, there is a message

**Comment by valdisvi** [comment]
Check, that you have dictionary files:
```
ls /usr/share/espeak-ng-data
```
and before calling espeak-ng, try to add this folder to the `PATH` variable:
```
export PATH=$PATH:/usr/share/espeak-ng-data
```

**Comment by tc-dl** [comment]
I switched to ubuntu 16.4 there it worked. but there is no PCAudioLib it what is needed? I hope after you edit the dictionary files will work.

**Comment by jaacoppi** [comment]
Closed as a duplicate.
