### ISSUE TITLE
How to change default voice

### ISSUE THREAD

**Issue by OakLD** [espeak-ng/espeak-ng#719]
I wonder, how to change default voice? I couldn't find anything about it anywhere on the internet.

I don't mean how to change it with -v, but really the default voice (which comes quite terrible). Since I use it with speech-dispatcher and that is called by another software, I cannot pass any arguments.

If anyone has some comparison, I wonder, can espeak-ng come quality-wise close to the Japanese nittech NTS voices on Festival?

**Comment by DidierSpaier** [comment]
Changes can be made in /etc/speech-dispatcher/speechd.conf  or (easier) in the Orca preferences GUI if you use Orca.

**Comment by valdisvi** [comment]
If you have installed [MBROLA](https://en.wikipedia.org/wiki/MBROLA) engine and some of [MBROLA voices](https://github.com/numediart/MBROLA-voices/), then you can use  them.

**Comment by mercster** [comment]
Hey folks... in Ubuntu i have a zillion files in /etc/speech-dispatcher and downwards... I can't tell how the default voice is getting set.  I want to change it to "robert".  The default voice on my system sounds like MALE3/en-d , but I've tried replacing "en-d" for "robert" in the espeak-generic.conf and it's not changing the default. Can anyone help me?

Thanks.

**Comment by OakLD** [comment]
@valdisvi  I wonder, how do you set speech-dispatcher to use `MBROLA` engine directly (i.e. not via `espeak` or `festival`). It seems that is what you suggest and should be possible. I have it installed, but it isn't mentioned in the `speech-dispatcher` configuration file (like many other engines). When I try a wild guess, it doesn't work:

```
 #AddModule "espeak"       "sd_espeak"   "espeak.conf"
 #AddModule "espeak-ng"    "sd_espeak-ng" "espeak-ng.conf"
 AddModule "mbrola"    "sd_mbrola" "mbrola.conf"
 #AddModule "festival"     "sd_festival"  "festival.conf"
 #AddModule "flite"        "sd_flite"     "flite.conf"
```
I couldn't google anything either...

**Comment by OakLD** [comment]
@DidierSpaier I don't think so. This only defines what engine and what setting to set the dispatcher itself to. But there are files in `~/.config/speech-dispatcher/modules/` for each engine, i.e. `festival.conf`, or in this case `espeak.conf`, to set engine-specific stuff. I believe the voices should be set here. I think it should be here you set i.e. `MALE1` to `mb-us1` Unfortunately, this file does not provide any example to set that and I failed to google anything on this subject.

**Comment by DidierSpaier** [comment]
n@OakLD: Do you use Orca? If yes, and you have recent versions of speech-dispatcher and Orca, in the Preferences GUI of Orca in the Voices Tab you can choose the synthesizer, then the language, then the voice.  Obviously the choices depend on which synthesizers and voices you have installed 

For instance here (Slint64-14.2.1..2) if I choose  as synthesizer espeak-ng and as language en-US i can choice as voice (labeled Person) English (America) + Robert.

If I choose as synthesizer espeak-ng-mbrola-generic and as language en-us I can choose among us1, us2 or us3  (that map respectively to us1, us2 or us3).

To get a good voice you could also get  the voxin synthesizer and associated voices from oralux.org.

To know what's available to you, please indicate which distribution and version you are using, and if not Orca which screen reader. Is it speechd-up or fenrir?

If not using Orca, setting a specific voice for speech-dispatcher is currently tricky, because it is only possible editing a config file to map this voice whit a "generic" one line MALE3. 

I could file an issue about that against speech-dispatcher but I am pretty sure that Samuel will respond "patches are welcome" and I am currently busy <smile>.

As an aside, the issue you filed here would better fit in the speech-dispatcher mailing list anyway, as it is not specific to espak-ng.

Cheers,

Didier

**Comment by DidierSpaier** [comment]
Instead of:
If I choose as synthesizer espeak-ng-mbrola-generic and as language en-us I can choose among us1, us2 or us3 (that map respectively to us1, us2 or us3).

Please read:
If I choose as synthesizer espeak-ng-mbrola-generic and as language en-us I can choose among us1, us2 or us3 (that map respectively to mb-us1, mb-us2 or mb-us3).

**Comment by OakLD** [comment]
No I don't have `Orca` installed and unfortunately it is not related to my issue and can't help me. I purchased a software and for that software a plugin (I had a choice of 1 for Linux, unfortunately), that works with `speech-dispatcher` only. So I have free hands for what stands beyond `speech-dispatcher`, but I can't replace it. The default `espeak` voice is so horrible it's not really understandable. So I'm simply after better TTS voice quality, but I don't need perfect, just not that horrible. I'd say `MBROLA` is minimum [acceptable quality](https://postimg.cc/N9d8k1zx).

I'm quite confused, whether I can set a default voice in `espeak` and also whether I can set them for `espeak` in `speach-dispatcher` (I know this 2nd part is a bit off topic here, I didn't ask for it originally, but since it was brought out...).

**Comment by DidierSpaier** [comment]
Then I can probably help, but only if you tell exactly which speech-dispatcher version you have installed and which synthesizers and voices you have. Still the exact version of your distribution and version will give clues. Also it would be useful to know your /etc/speech-dispatcher.speechd.conf file and the content of /etc/speech-dispatcher/modules. Fell free to send me this information privately @ didier at slint dot fr. Out of curiosity, which is this software you bought? I am interested as the maintainer of an accessible Linux distribution to know what is available.

Cheers,

Didier

**Comment by DidierSpaier** [comment]
I meant /etc/speech-dispatcher/speechd.conf

**Comment by OakLD** [comment]
Oh, it's not secret. I have OpenSUSE Leap 15.1 Linux, espeak 1.48.04-lp151.2.3, espeak-ng 1.49.2-lp151.4.3, speech-dispatcher 0.8.8-lp151.3.6.1. The lp151 indicates all of those are default Leap 15.1 packages from the official OpenSUSE repositories. The speechd.conf in short:
`
LogLevel  3
LogDir  "default"
DefaultVolume 100
AddModule "espeak"       "sd_espeak"   "espeak.conf"
`

**Comment by DidierSpaier** [comment]
Sorry then I'm afraid you are out of luck with OpenSuse. Here is why.

I had a look at the packages you mention from the official repository (I ma not running this distribution) and unless I miss something
- espeak and espeak-ng do not include the Klatt variants like Robert (and you don't have the espeak-ng module of speech-dispatcher)
- there is no packages for the mbrola voices, only the engine.
- there is no package for the svox-pico voices 
- maybe you could get a voxin synthesizer from Oralux and associated voices, but I don't know if they have packages for OpenSuse (and the voxin website is off-line for maintenance at the moment so I can't check now).

So, the only way to get decent voices as far as I know is to use another Linux distribution, for 
instance Debian, or Slint (that I maintain), or Arch.

**Comment by OakLD** [comment]
My mistake, I forgot to mention `speech-dispatcher-module-espeak` 0.8.8-lp151.3.6.1. It provides:
```
/etc/speech-dispatcher/modules/espeak.conf
/usr/lib64/speech-dispatcher-modules/sd_espeak
```
You're right that there's no `espeak-ng` module for `speech-dispatcher` available in OpenSUSE repositories. `MBROLA` is available, but nly German voices (!) are supplied. However, I installed some from Fedora. They're noarch, so it should be fine.
There are also some packages I dind't install (didn't think they're needed), such as `espeak-ng-compat` and `espeakedit`.
It's really pitty that I got my `festival` working with relatively quality HTS voices, I got my `espeak` working with `MBROLA` (yes, they're working when forced via a parameter in command line), but neither I can get it working with `speech-dispatcher`...
It's so desperate that I'm looking into option to write my own plugin. But it's not a small job...

**Comment by guest271314** [comment]
Note, installing a modified version of `espeak-ng`, e.g., following the instructions for building `espeak-ng` does not result in those changes being reflected at `/usr/lib/speech-dispatcher-modules/sd_espeak-ng`, in part

`libespeak-ng.so.1_ITM_deregisterTMCloneTable__gmon_start___ITM_registerTMCloneTableespeak_SetVoiceByNameespeak_Initializeespeak_SetSynthCallbackespeak_Infoespeak_SetPunctuationListespeak_SetUriCallbackespeak_ListVoicesespeak_SetParameterespeak_Synthespeak_Cancelespeak_Terminatelibsndfile.so.1sf_commandsf_opensf_strerrorsf_read_shortsf_closelibdotconf.so.0dotconf_createdotconf_cleanupdotconf_command_looplibglib-2.0.so.0g_strndupg_string_appendg_malloc0_ng_string_newg_utf8_strchrg_strdelimitg_str_has_prefixg_strdupg_strfreevg_strstr_leng_queue_peek_head_linkg_queue_freeg_malloc0g_string_append_printfg_reallocg_strsplitg_utf8_skipg_memdupg_queue_push_tailg_convertg_queue_free_fullg_convert_with_fallbackg_strcmp0g_string_freeg_utf8_validateg_mallocg_slist_appendg_file_testg_queue_get_lengthg_queue_is_emptyg_strdup_printfg_queue_newg_slist_removeg_usleeplibltdl.so.7lt_dlexitlt_dlsymlt_dlcloselt_dladvise_initlt_dlsetsearchpathlt_dlpreload_defaultlt_dladvise_destroylt_dladvise_extlt_dladvise_globallt_dlopenadviselt_dlerrorlt_dlinitlibpthread.so.0pthread_cond_destroypthread_createpthread_cancelpthread_joinpthread_setcanceltypepthread_mutex_initpthread_setcancelstatepthread_cond_broadcastsem_initpthread_cond_waitpthread_mutex_unlockpthread_cond_signalsem_postpthread_sigmasksem_trywaitpthread_cond_init__errno_locationsem_destroypthread_mutex_lockpthread_mutex_trylockpthread_mutex_destroypthread_exitsem_waitlibc.so.6_IO_stdin_usedfflush__printf_chkfopenstrncmpsigprocmasksigfillsetstdin__assert_failstrtokstrtolstrlenungetc__fprintf_chksigaddsetctimestdoutfputcfputsfclosestderrsigdelsetfwritegettimeofday__cxa_finalize_IO_getcstrcmp__libc_start_main__stack_chk_fail_edata__bss_startmodule_stopmodule_send_asynchronousmodule_recode_to_isomodule_parent_dp_readmodule_index_markcurrent_index_markmodule_strip_ssmlstr2ESpellModemodule_initmodule_sigunblockusrspd_audio_opendo_charmodule_parent_wforkmodule_list_voicesEspeakMaxRate_cb_fp_hwmodule_report_event_endstr2intpriorityEspeakPunctuationList_cbmodule_strip_punctuation_someEPunctMode2strmodule_report_event_stopdo_speakdo_stopmodule_play_filedo_debugmodule_report_event_begindo_messageDebugspd_getlinespd_audio_set_logleveldo_pausedo_audiomodule_parent_dp_initlt__PROGRAM__LTX_preloaded_symbolsEspeakMinRate_cbmodule_child_dp_readmodule_report_index_markmodule_sigblockallconfigfiledo_setspd_audio_set_volumemodule_audio_idmodule_speakmodule_tts_outputstr2EPunctModemodule_terminate_threadmodule_pausemodule_parent_dp_closemodule_child_dp_writeESpellMode2strstr2ECapLetRecognmsg_settingsdo_list_voicesspd_audio_stopspd_audio_closemodule_child_dp_initdo_sound_icon__data_startdo_loglevelmodule_strip_punctuation_defaultmodule_parent_dp_writeplayback_queue_conditionmodule_child_dp_closeEVoice2strECapLetRecogn2strCustomDebugFilelog_level__libc_csu_initEspeakNormalRate_cbEspeakSoundIconVolume_cbEspeakCapitalPitchRise_cbdo_quitstr2EVoicemodule_audio_initmodule_parent_wait_continueEspeakAudioQueueMaxSize_cbmsg_settings_oldmodule_num_dc_optionsspd_audio_get_playcmdset_speaking_thread_parametersmodule_stdout_mutex__libc_csu_finimodule_add_config_optionmodule_sigblockusrspd_audio_playmodule_loaddo_keyEspeakSoundIconFolder_cbEspeakAudioChunkSize_cbmodule_dc_optionsmodule_report_event_pauseEspeakListVoiceVariants_cbmodule_get_message_partmodule_closeDebug_cblibsndfile.so.1.0GLIBC_2.1GLIBC_2.0GLIBC_2.3.2GLIBC_2.4GLIBC_2.1.3GLIBC_2.3.4`

For example, in an attempt to set SSML parsing on by default for Web Speech API so that `--enable-speech-dispatcher` flag at Chromium will use the modified version of `espeak-ng`, removed all `espeak` and ` espeak-ng` packages, added ` | espeakSSML` to L344 at espeak-ng.c, installed using `make`, tested `espeak-ng <speak>test</speak>` at terminal which output audio "test" without passing `-m` flag. 

`$ spd-say <speak>test</test>` does not output the same audio, SSML is not enabled without `x` option, `sd_espeak-ng` appears to be an entirely different version of `espeak-ng` unrelated to installed `espeak-ng` by packages. 

Installing `python3-speechd` then running `spd-conf` creates `~/.config/speech-dispatcher/speechd.conf` where there are fields available for setting `# ----- VOICE PARAMETERS -----`, `DefaultVoiceType`, `DefaultLanguage`. `~/.config/speech-dispatcher/modules/espeak-ng.conf` contains fields for setting `EspeakListVoiceVariants`.

**Comment by jaacoppi** [comment]
not an espeak-NG issue. Closing.

**Comment by AnthonyWJones** [comment]
So in other words Linux effing sucks. Got it.

**Comment by sthibaul** [comment]
All of that really belonged to the *speech-dispatcher* issue tracker... I'll transfer it there

> It's so desperate that I'm looking into option to write my own plugin. But it's not a small job...

Isn't it possible to just install a more recent version of speech-dispatcher? Version 0.8.8 was released 5 years ago...

> When I try a wild guess, it doesn't work:
>
> #AddModule "espeak"       "sd_espeak"   "espeak.conf"
> #AddModule "espeak-ng"    "sd_espeak-ng" "espeak-ng.conf"
> AddModule "mbrola"    "sd_mbrola" "mbrola.conf"

Indeed, since mbrola doesn't provide an API it doesn't make sense to write a native module for it. At the time speech-dispatcher was using a generic module for it, see this line in the configuration:

```
#AddModule "espeak-mbrola-generic" "sd_generic" "espeak-mbrola-generic.conf"
```

You can uncomment that line to get it loaded by default.

Also, posting the speech-dispatcher.log file would help us understand what is going wrong on that system.

**Comment by sthibaul** [comment]
> I'll transfer it there

Err, except it seems github doesn't allow that :/ Perhaps just open an issue there so we can continue the discussion without bothering espeak people.

**Comment by RangerMauve** [comment]
It seems chromium is bypassing my speech-dispatcher settings and is calling espeak-ng directly. Is there a config somewhere to set the default voice? Or perhaps an environment variable?

**Comment by ell1e** [comment]
If anybody else finds this via web search and is on Alpine Linux, this is what worked for me:

1. Install these packages: `espeak-ng speech-dispatcher mbrola-voices mbrola`
2. Open `/etc/speech-dispatcher/speechd.conf` as root (e.g. via `sudo nano /etc/speech-dispatcher/speechd.conf`) and uncomment this line: `#AddModule "espeak-ng-mbrola-generic" "sd_generic"   "espeak-ng-mbrola-generic.conf"` so that it looks like this: `AddModule "espeak-ng-mbrola-generic" "sd_generic"   "espeak-ng-mbrola-generic.conf"`
3. **Important:** Restart speech dispatcher. For me, `killall speech-dispatcher` and then restarting the programs that were using it worked.
4. You should now have an mbrola voice in all speech-dispatcher programs! (The ones that actually use speech-dispatcher, rather than espeak directly.)

**Comment by eabase** [comment]
# Bump

There is no `embrola` packages for Debian, AFAICT.


But there are too many config file options from the `speech-dispatcher-espeak-ng` package:
```bash 
# tree -L 2 /etc/speech-dispatcher

/etc/speech-dispatcher
├── clients
│   └── emacs.conf
├── modules
│   ├── cicero.conf
│   ├── dtk-generic.conf
│   ├── epos-generic.conf
│   ├── espeak.conf
│   ├── espeak-mbrola-generic.conf
│   ├── espeak-ng.conf
│   ├── espeak-ng-mbrola.conf
│   ├── espeak-ng-mbrola-generic.conf
│   ├── festival.conf
│   ├── flite.conf
│   ├── llia_phon-generic.conf
│   ├── mary-generic.conf
│   ├── mimic3-generic.conf
│   ├── openjtalk.conf
│   └── swift-generic.conf
└── speechd.conf


```

So not clear what to edit, since there is no embrola. 

@alex19EP ?
