### ISSUE TITLE
Improved Interlingua voice

### ISSUE THREAD

**Issue by nesrad** [espeak-ng/espeak-ng#811]
Hi, I've created the file **ia_list** to improve pronunciation for the ia voice. I'm not sure how to add it to your project, so I'll just leave it here.
[ia_list.zip](https://github.com/espeak-ng/espeak-ng/files/5115207/ia_list.zip)

Since Interlingua shares its sounds with the romance languages, I was wondering what steps would be needed to use existing mbrola voices like Italian.

**Comment by valdisvi** [comment]
Thanks for contribution! It is included into the project with commit 5deac40.
Some notes:
1. as word list is very long, it is put in file `ia_listx`, where extended list of words is usually stored, except
2. pronunciation of numbers are put into updated `ia_list` file.
3. file had two different rules for the same word:
```
le	$nounf $u+
le 	$verb $verbextend $u
```
I left only first entry in `ia_list` file.

4. There were capital first letters used for written words, these were converted to lowercase, because espeak-ng rules don't care about case of letters in written form. If you need to care about them, additional [flag](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md#flags) (e.g. `$capital` or `$allcaps`) should be added after pronunciation.

To use MBROLA Italian voice for Interlingua, look [MBROLA voices](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md) guide and [mb-it1](https://github.com/espeak-ng/espeak-ng/blob/master/espeak-ng-data/voices/mb/mb-it1) and [it1](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/mbrola/it1) files as examples.
