### ISSUE TITLE
Hebrew is not supported

### ISSUE THREAD

**Issue by NirAbel** [espeak-ng/espeak-ng#825]
hello,
I'm trying to use the Hebrew language but it's not work for me.
for example:
espeak -v he  "בוקר טוב"

return: 
Error: The specified espeak-ng voice does not exist.

please help me.
Thank you!
Nir

**Comment by valdisvi** [comment]
Currently Hebrew language is available only in development version of eSpeak NG. You can [build eSpeak NG from source code](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md), or test it [on-line here](https://odo.lv/Espeak).

**Comment by OrionRandD** [comment]
I am running debian and I have:
 $ which espeak
/usr/bin/espeak
-> user@underground 
~ $ which espeak-ng
/usr/bin/espeak-ng

I am kind of confused. 
Which one should use? 
It seems the espeak-ng is better than espeak...
Should I remove espeak or make a symbolic link from espeak-ng voices to
espeak voices?
If so, how do I do it?
I also have mbrola voices for Hebrew and Arabic. 
How do I use them with espeak?

**Comment by valdisvi** [comment]
If you have installed espeak-ng package, then `espeak` is just symbolic link to `espeak-ng`
```
$ which espeak
/usr/bin/espeak
$ ls -l /usr/bin/espeak
lrwxrwxrwx 1 root root 9 jūn 19 08:57 /usr/bin/espeak -> espeak-ng
```

**Comment by OrionRandD** [comment]
> If you have installed espeak-ng package, then `espeak` is just symbolic link to `espeak-ng`
> 
> ```
> $ which espeak
> /usr/bin/espeak
> $ ls -l /usr/bin/espeak
> lrwxrwxrwx 1 root root 9 jūn 19 08:57 /usr/bin/espeak -> espeak-ng
> ```

I dont think it is the case here:

~ $ espeak --version
eSpeak text-to-speech: 1.48.15  16.Apr.15  Data at: /usr/lib/x86_64-linux-gnu/espeak-data

~ $ espeak-ng --version
eSpeak NG text-to-speech: 1.50  Data at: /usr/lib/x86_64-linux-gnu/espeak-ng-data

~ $ ls -l /usr/bin/espeak
-rwxr-xr-x 1 root root 27K jan  1  2021 /usr/bin/espeak*

So, the question about removing espeak or not...

**Comment by valdisvi** [comment]
If you have installed both, in most of cases you can remove espeak, because from command line and API perspective, espeak-ng is pretty compatible with espeak. Espeak-ng hase more features, but existing are almost the same, although, there have been some reports, where unintended changes were caught and fixed.

**Comment by OrionRandD** [comment]
> If you have installed both, in most of cases you can remove espeak, because from command line and API perspective, espeak-ng is pretty compatible with espeak. Espeak-ng hase more features, but existing are almost the same, although, there have been some reports, where unintended changes were caught and fixed.

I have discovered why I have espeak and I cannot remove it.
It is because ebook-speaker - a wonderful cli app is tied to it and espeak-ng knows nothing about it  :(

 # apt purge espeak
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  espeak-data libespeak1
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ebook-speaker* espeak*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 614 kB disk space will be freed.
Do you want to continue? [Y/n]

 # apt install ebook-speaker
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  espeak
Suggested packages:
  calibre tesseract-ocr | cuneiform unrtf
The following NEW packages will be installed:
  ebook-speaker espeak
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 231 kB of archives.
After this operation, 614 kB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by OrionRandD** [comment]
I made a symlink from espeak-ng to espeak after uninstalling espeak
/usr/bin/espeak-ng  --> /usr/bin/espeak

But, after installing ebook-speaker again, the espeak older version took over again destroying the symlink  :(

 # espeak --version
eSpeak text-to-speech: 1.48.15  16.Apr.15  Data at: /usr/lib/x86_64-linux-gnu/espeak-data

 # espeak-ng --version
eSpeak NG text-to-speech: 1.50  Data at: /usr/lib/x86_64-linux-gnu/espeak-ng-data

**Comment by valdisvi** [comment]
Best way would to solve this would be to reporting it to ebook-speaker package maintainer.

**Comment by OrionRandD** [comment]
> Best way would to solve this would be to reporting it to ebook-speaker package maintainer.

I think that Jos Lemmens <jos@jlemmens.nl> 
Is also the creator of espeak 
http://www.jlemmens.nl/
Now I understand why ebook-speaker is linked to espeak...

**Comment by valdisvi** [comment]
Creator of eSpeak is [Jonathan Duddington](http://espeak.sourceforge.net/).

**Comment by OrionRandD** [comment]
> Creator of eSpeak is [Jonathan Duddington](http://espeak.sourceforge.net/).

I've sent them an email to see if they can help solving this issue...
I will just wait...

**Comment by jaacoppi** [comment]
> > Creator of eSpeak is [Jonathan Duddington](http://espeak.sourceforge.net/).
> 
> I've sent them an email to see if they can help solving this issue...
> I will just wait...

You probably won't get an answer from Jonathan Duddington. He hasn't been online for many years.


> I also have mbrola voices for Hebrew and Arabic.
> How do I use them with espeak?

See `docs/mbrola.md`

**Comment by OrionRandD** [comment]
On Sat, Jul 10, 2021 at 11:31:18PM -0700, jaacoppi wrote:
>        Creator of eSpeak is [1]Jonathan Duddington.
> 
>      I've sent them an email to see if they can help solving this issue...
>      I will just wait...
> 
>    You probably won't get an answer from Jonathan Duddington. He hasn't been
>    online for many years.
> 
>      I also have mbrola voices for Hebrew and Arabic.
>      How do I use them with espeak?
> 
>    See docs/mbrola.md

I've seen that. It says we have support for Arabic, but Hebrew :(

espeak-ng -var1 and espeak-ng -var2 work, but espeak-ng -vhb1 and espeak-ng -vhb2 do not.

How do you make Hebrew voice work then?

**Comment by jaacoppi** [comment]
> I've seen that. It says we have support for Arabic, but Hebrew :( espeak-ng -var1 and espeak-ng -var2 work, but espeak-ng -vhb1 and espeak-ng -vhb2 do not. How do you make Hebrew voice work then?

Read the previous messages in this thread:
> Currently Hebrew language is available only in development version of eSpeak NG. You can [build eSpeak NG from source code](https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md), or test it [on-line here](https://odo.lv/Espeak).

**Comment by OrionRandD** [comment]
I saw that and I tried to edit my answer to you. But couldn't.
Thx anyway...
Better to wait then...

**Comment by omeritzics** [comment]
Hello, thank you for your hard work and for adding Hebrew!
Hebrew works good, but it still needs improvements.
For example, the word דוגמה (sounds like "doog-ma") sounds like "Thm".

**Comment by OrionRandD** [comment]
> Hello, thank you for your hard work and for adding Hebrew!
> Hebrew works good, but it still needs improvements.
> For example, the word דוגמה (sounds like "doog-ma") sounds like "Thm".
> 
> _Edit:_ The letter Da-let (ד) sounds like "th", while this consonant doesn't exist in Hebrew.
> As Hebrew uses an ABJAD writing system, Espeak-NG should learn when to pronounce vowels
> and when to not, because it does not read words with vowels when the vowel diacritic (Niqqud).

Could you post a command here, for me to test?
In my system it only speaks letter by letter and not the word as an unit

espeak-ng -vhr דוגמה

:(

**Comment by omeritzics** [comment]
I did not use the command line, but used the URL @valdisvi provided.

**Comment by OrionRandD** [comment]
> I did not use the command line, but used [the URL @valdisvi provided](https://odo.lv/Espeak).

All right. I thought that the CLI was already working...
Thx

**Comment by jaacoppi** [comment]
Hebrew language is "he". Don't use "hr", that's for Croatian.

Use -X for debugging:

espeak-ng -vhe " דוגמה" -X
Translate 'דוגמה'
 36     ד       [d]

 36     ו       [v]

 36     ג       [g]

 36     מ       [m]

 36     ה       [?]

dvgm?

The rules for pronouncing a letter are in dictsource/he_rules.  See docs/dictionary.md for documentation.

Without knowing any Hebrew, it looks like either "ו" is set incorrectly to "v" or the rule for "דו" is missing.

.group ו
       ו        v   
       וּ        u 
       _)וּ        u
       וֹ        o   
       _) וֹ        o
       וו        w

.group  ד
       ד        d
       דַ        da
       דֵ        de 
       דֶ        de
       דְ        d
       דִ        di
       דוֹ        do 
       די        di
       דוּ        du
       דׇ        do  
       דָ        da
       דּ        d
       ד'        D
       דַ'        Da
       דֵ'        De
       דֶ'        De
       דְ'        D
       דִ'        Di
       ד'וֹ        Do
       ד'י        Di
       ד'וּ        Du
       דׇ'        Do
       דָ'        Da

**Comment by OrionRandD** [comment]
espeak-ng -vhe " דוגמה" -X
Error: The specified espeak-ng voice does not exist.

**Comment by hozosch** [comment]
Not VHE, just he

**Comment by OrionRandD** [comment]
espeak-ng -he "דוגמה" -X

eSpeak NG text-to-speech: 1.50  Data at:
/usr/lib/x86_64-linux-gnu/espeak-ng-data

espeak-ng [options] ["<words>"]

-f <text file>   Text file to speak
--stdin    Read text input from stdin instead of a file

If neither -f nor --stdin, then <words> are spoken, or if none then text
is spoken from stdin, each line separately.

-a <integer>
  Amplitude, 0 to 200, default is 100
-d <device>
  Use the specified device to speak the audio on. If not specified, the
  default audio device is used.
-g <integer>
  Word gap. Pause between words, units of 10mS at the default speed
-k <integer>
  Indicate capital letters with: 1=sound, 2=the word "capitals",
  higher values indicate a pitch increase (try -k20).
-l <integer>
  Line length. If not zero (which is the default), consider
  lines less than this length as end-of-clause
-p <integer>
  Pitch adjustment, 0 to 99, default is 50
-s <integer>
  Speed in approximate words per minute. The default is 175
-v <voice name>
  Use voice file of this name from espeak-ng-data/voices
-w <wave file name>
  Write speech to this WAV file, rather than speaking it directly
-b   Input text encoding, 1=UTF8, 2=8 bit, 4=16 bit
-m   Interpret SSML markup, and ignore other < > tags
-q   Quiet, don't produce any speech (may be useful with -x)
-x   Write phoneme mnemonics to stdout
-X   Write phonemes mnemonics and translation trace to stdout
-z   No final sentence pause at the end of the text
--compile=<voice name>
  Compile pronunciation rules and dictionary from the current
  directory. <voice name> specifies the language
--compile-debug=<voice name>
  Compile pronunciation rules and dictionary from the current
  directory, including line numbers for use with -X.
  <voice name> specifies the language
--compile-mbrola=<voice name>
  Compile an MBROLA voice
--compile-intonations
  Compile the intonation data
--compile-phonemes=<phsource-dir>
  Compile the phoneme data using <phsource-dir> or the default phsource
directory
--ipa      Write phonemes to stdout using International Phonetic Alphabet
--path="<path>"
  Specifies the directory containing the espeak-ng-data directory
--pho      Write mbrola phoneme data (.pho) to stdout or to the file in
--phonout
--phonout="<filename>"
  Write phoneme output from -x -X --ipa and --pho to this file
--punct="<characters>"
  Speak the names of punctuation characters during speaking.  If
  =<characters> is omitted, all punctuation is spoken.
--sep=<character>
  Separate phonemes (from -x --ipa) with <character>.
  Default is space, z means ZWJN character.
--split=<minutes>
  Starts a new WAV file every <minutes>.  Used with -w
--stdout   Write speech output to stdout
--tie=<character>
  Use a tie character within multi-letter phoneme names.
  Default is U+361, z means ZWJ character.
--version  Shows version number and date, and location of espeak-ng-data
--voices=<language>
  List the available voices for the specified language.
  If <language> is omitted, then list all voices.
--load     Load voice from a file in current directory by name.
-h, --help Show this help.

**Comment by hozosch** [comment]
Oh, so it is with the v! Sorry, I'm not familiar with the command line. But "he" is the correct voice name!

**Comment by OrionRandD** [comment]
$ espeak-ng --voices|grep Arabic
 5  ar              --/M      Arabic             sem/ar
-> ***@***.*** 11:09:31
~ $ espeak-ng --voices|grep Hebrew
-> ***@***.*** 11:09:47
~ $

I do not have this "he" voice
"hr"  speaks the Hebrew letters correctly...

espeak-ng -vhr "דוגמה" -X

But not the word as an unit.

**Comment by OrionRandD** [comment]
espeak-ng -vhe "דוגמה" -X
Error: The specified espeak-ng voice does not exist.

**Comment by hozosch** [comment]
Are you sure you're running the latest development version?

**Comment by omeritzics** [comment]
Not sure. The used version is the version in [this website](https://odo.lv/Espeak).

**Comment by OrionRandD** [comment]
Do you mean that the last espeak-ng
comes with "he" voice as default?
Because I cannot see any "he" voice when I "apt-cache search espeak | grep
Hebrew"

I only have mbrola for Hebrew and Arabic
apt-cache search Hebrew| grep voice
mbrola-hb1 - Hebrew male voice for Mbrola
mbrola-hb2 - Hebrew female voice for Mbrola
-> ***@***.*** 11:23:06
~ $ apt-cache search Arabic| grep voice
mbrola-ar1 - Arabic male voice for Mbrola
mbrola-ar2 - Arabic male voice for Mbrola

**Comment by OrionRandD** [comment]
espeak-ng --version
eSpeak NG text-to-speech: 1.50  Data at:
/usr/lib/x86_64-linux-gnu/espeak-ng-data

**Comment by hozosch** [comment]
1.50, NVDA on Windows uses 1.51-dev. The version on odo.lv is always the latest one, not sure what's the problem there.

**Comment by OrionRandD** [comment]
Do you mean that my version is the right one?
I am on debian

**Comment by valdisvi** [comment]
`mbrola-hb1` and `mbrola-hb2` packages are data files for completely different [MBROLA](https://en.wikipedia.org/wiki/MBROLA) sound synthesizer. eSpeak NG can be used as a "front end" for it to do text-to-phoneme translation for MBROLA. Though it doesn't have configuration files for Hebrew. See more at [MBROLA Voices](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md)
I can create initial settings for it, but to make it usable, improvements will be needed by native speaker.

**Comment by OrionRandD** [comment]
There is something wrong in espeak-ng,
related to debian or the error is in the package itself.
Because,
espeak-ng --voices| less
does not show any "he"  - Hebrew - language
It only shows "hr" for Croatian.
But, if I use
espeak-ng -vhr "any Hebrew word"
this "hr", which is a Croatian voice, spells each Hebrew letter, but not
the entire word as unit.
Is the Croatian alphabet the same as the Hebrew alphabet?
Something is wrong then: either in espeak-ng or in the "hr" language
voice...
Can you install debian in a VM - say Virtualbox and test it?
Thx

**Comment by valdisvi** [comment]
There is nothing wrong with eSpeak NG. It uses ISO 639-1 or ISO 639-3 codes for languages, but some MBROLA voices do not follow these standards. `hr` is code for Croatian and `he` is for Hebrew. If eSpeak NG would have configuration files created for MBROLA voices (see my comment earlier), name for them would be `mb-hr1` or `mb-hr2`.

**Comment by OrionRandD** [comment]
Why then "hr"  spells Hebrew letters?
I have tested in debian and archlinux
And there are no "he" voices for espeak-ng

**Comment by hozosch** [comment]
Any language does that. It is defined in en_list, but not sure what makes the other languages use those entries.

**Comment by hozosch** [comment]
I mean the spelling out of the letters.

**Comment by OrionRandD** [comment]
What I know is that there is something wrong...
If you being a developer does not know... So, who knows?
Is my versions of espek-ng in debian and archlinux the right one?
If so, should this versions have "he" - Hebrew support on it?
If so, why I do not see this when I install espeak-ng in both systems?

**Comment by jaacoppi** [comment]
> What I know is that there is something wrong... If you being a developer does not know... So, who knows? Is my versions of espek-ng in debian and archlinux the right one? If so, should this versions have "he" - Hebrew support on it? If so, why I do not see this when I install espeak-ng in both systems?

Read through the posts in this thread. For Hebrew support, you'll need 1.51-dev. Hebrew support has been added after version 1.50. Version 1.51 hasn't been released yet. That's why it's called 1.51-dev.

I do not know which versions Debian or Arch linux have. If you want them to have the latest version (1.51-dev from git), ask them to include it. The other option is to build from source. The instructions are in https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md

Second question, why do all other languages know the Hebrew alphabet? It's because espeak-ng is programmed to spell out the letters of unknown alphabets one by one. It doesn't matter if the writing is in  Hebrew, Telugu, Chinese, Greek or any other supported language. Espeak-ng recognises that this script is not native to this language. Note that this is a different discussion for a different thread.

**Comment by valdisvi** [comment]
@OrionRandD, please read carefully, what I already wrote in [previous comment](https://github.com/espeak-ng/espeak-ng/issues/825#issuecomment-889213617):

> `hr` is code for Croatian and `he` is for Hebrew of natively synthesized eSpeak NG voices.

If you use different voice, which doesn't have defined pronunciation of characters for other language, it is nothing wrong, if spells unicode names for these characters. You can get the same behaviour, if you use English, Latvian or other language instead of Hebrew e.g.:
```
espeak-ng -ven "דוגמה" -X
espeak-ng -vlv "דוגמה" -X
```

**Comment by OrionRandD** [comment]
Ok, thanks.
Debian and Archlinux install 1.50.
I will just wait for 1.51...
Fair enough thx a lot to explain my questions...

**Comment by data-man** [comment]
@OrionRandD 
In Arch Linux you can use espeak-ng-git from AUR.

**Comment by valdisvi** [comment]
I have added initial support for Hebrew MBROLA voices in eSpeak NG. You are welcome to improve it by yourself e.g. [online here](https://odo.lv/Espeak?eslang=-vmb-hb1&output=-w&debug=-x&text=[[Sh'alom]]&formmethod=get). Phonetic writing (`[[...]]`) is used in online demonstration because:
1. Translation from Hebrew text to phonemes should be greatly improved in [he_rules](https://github.com/espeak-ng/espeak-ng/blob/master/dictsource/he_rules) file. For information look at [Text to Phoneme Translation](https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md).
2. eSpeak NG phoneme to MBROLA phoneme mapping should be improved (only dummy stub file is created) and many phoneme mappings are missing in [he](https://github.com/espeak-ng/espeak-ng/) file. For information look at [MBROLA Voices](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md) and [Readme for hb1](https://github.com/numediart/MBROLA-voices/tree/master/data/hb1) and [Readme for hb2](https://github.com/numediart/MBROLA-voices/tree/master/data/hb2).

More general information:
* [General contribution guide](https://github.com/espeak-ng/espeak-ng/blob/master/docs/contributing.md)
* [eSpeak NG online testing guide](https://odo.lv/EspeakGuide)

**Comment by OrionRandD** [comment]
Great! If someone knows anyone in
Techinion University - in Haifa, Israel, perhaps a teacher could take this
project there...

**Comment by morrisalp** [comment]
We found that there are many issues in the current eSpeak NG Hebrew phoneme conversion.
Please see our recent project and paper for an approach to Hebrew grapheme-to-phoneme conversion that might be relevant.
Project: https://thewh1teagle.github.io/phonikud-paper/
Paper: https://arxiv.org/pdf/2506.12311
Github: https://github.com/thewh1teagle/phonikud

**Comment by morrisalp** [comment]
> > We found that there are many issues in the current eSpeak NG Hebrew phoneme conversion. Please see our recent project and paper for an approach to Hebrew grapheme-to-phoneme conversion that might be relevant. Project: https://thewh1teagle.github.io/phonikud-paper/ Paper: https://arxiv.org/pdf/2506.12311 Github: https://github.com/thewh1teagle/phonikud
> 
> Do you mean that espeak-NG will speak proper Hebrew anytime soon? Or you just wanted to point me the issues with Hebrew language in espeak-NG? Thx a ton.

We find issues in Hebrew phoneme conversion with espeak-NG and we propose our own approach for this.
I am not involved in espeak-NG development, but maybe this will help anyone who is working on this.
