### ISSUE TITLE
Adding Pashto Language

### ISSUE THREAD

**Issue by YousafKhan1** [espeak-ng/espeak-ng#892]
I would like to add the pashto language which is same to Arabic and Urdu language so now I downloaded the source code how to compile it in windows for to test the files of pashto language.
thanks

**Comment by jaacoppi** [comment]
For adding languages, see: https://github.com/espeak-ng/espeak-ng/blob/master/docs/add_language.md. In your case it's probably easiest to make a copy of Arabic or Urdu and change things instead of starting from empty files.

For building, see: https://github.com/espeak-ng/espeak-ng/blob/master/docs/building.md and https://github.com/espeak-ng/espeak-ng/issues/891.

**Comment by YousafKhan1** [comment]
Bundle of thanks
I will try to build it if there was an error then I will share with you.
I am using VS 2017

**Comment by YousafKhan1** [comment]
Hi 
I run the project in MSVS 2017 but I faced with many errors
the errors are

Error C1083 Cannot open include file: 'stddef.h': No such file or directory	libespeak-ng	c:\users\yousaf tarakai\downloads\espeak-ng\src\ucd-tools\src\case.c	27	

Error C1083 Cannot open include file: 'ctype.h': No such file or directory	libespeak-ng	c:\users\yousaf tarakai\downloads\espeak-ng\src\libespeak-ng\compiledata.c	22	
.........
and so on
please if you have a suggestion please share with me.

**Comment by mablue** [comment]
#2051 
#2080
