### ISSUE TITLE
Dengler, Binghamton pronounced differently based on capitalization

### ISSUE THREAD

**Issue by codeofdusk** [espeak-ng/espeak-ng#895]
When "Dengler" and "Binghamton" are written with an initial capital letter, they are pronounced correctly. However, when written in all lowercase, they are pronounced incorrectly (i.e. "Dengler" is pronounced correctly but "dengler" isn't, same with Binghamton and binghamton).

**Comment by jaacoppi** [comment]
This is related to:
https://github.com/espeak-ng/espeak-ng/issues/620
https://github.com/espeak-ng/espeak-ng/issues/622

Since both words have already been updated for upper case letters I can think of no reason to change lower case pronunciation as well.

I'll keep this open for discussion for a little while first..

**Comment by 0x5066** [comment]
This makes me curious as to why it makes a difference in pronunciation if the word is in lowercase or uppercase

**Comment by jaacoppi** [comment]
In general, some words actually have a different pronunciation. Polish (people) vs (to) polish for example. That's why $capital exists and is explained in docs/dictionary.md.

For these two words I guess there are no words that could cause confusion.
