### ISSUE TITLE
add Direct Boot support for Android so espeak-ng can be used with TalkBack before the initial unlock

### ISSUE THREAD

**Issue by thestinger** [espeak-ng/espeak-ng#917]
More information:

https://developer.android.com/training/articles/direct-boot

https://github.com/GrapheneOS/platform_packages_apps_Updater is a trivial example of using this.

You need to mark a subset of the functionality as direct boot aware and make sure it's capable of running in that state. A minimal amount of data needs to be migrated to being stored in device encrypted storage via the APIs for this. No sensitive user data should be marked that way. The voice setup and other configuration is what's expected to be there. There shouldn't be any kind of history, stats or other sensitive data in device encrypted storage though.

The open source release of TalkBack is available here and has Direct Boot support:

https://github.com/google/talkback

**Comment by PatrykMis** [comment]
It will be very important enhancement for blind FOSS community, GNU/GPL enthusiasts and promoting free software.
Why? Because currently, there is no open source TTS which has this feature.
For example, as a blind human beeing, currently I'm using Lineage with MicroG+Talkback (my plan is to move to GrapheneOS) built from source and I can't (and don't want to) use Google Text-To-Speech, mainly because it is closed proprietary software. So my biggest issue is when I boot my OS and require sighted assistance to enter my pin and then TTS starts.

**Comment by PatrykMis** [comment]
https://www.bountysource.com/issues/98057192-add-direct-boot-support-for-android-so-espeak-ng-can-be-used-with-talkback-before-the-initial-unlock
