### ISSUE TITLE
Shan Language tone number doesn't show up correctly.

### ISSUE THREAD

**Issue by ronaldaug** [espeak-ng/espeak-ng#953]
As we define [tone numbers here](https://github.com/espeak-ng/espeak-ng/blob/40b78f5183f66958b333d8a54f0ab25a9576be5e/dictsource/shn_rules#L332) but it seems it doesn't work correctly. 

If I run this `မႃႇ မႃႈ မႃး မႃႉ` , it should output `ma2 ma3 ma4 ma5`. But currently it outputs like `m'a1 m'a1 m'a4 m'a1`. 

And how can I make these tones ` ႇ ႈ း ႉ ႊ ` always follow as the last character? Thanks.

**Comment by valdisvi** [comment]
I'm not experienced with tonal languages. Maybe you can compare [Shan](https://github.com/espeak-ng/espeak-ng/blob/40b78f5183f66958b333d8a54f0ab25a9576be5e/src/libespeak-ng/tr_languages.c#L1585) with e.g. [Chinese](https://github.com/espeak-ng/espeak-ng/blob/40b78f5183f66958b333d8a54f0ab25a9576be5e/src/libespeak-ng/tr_languages.c#L1594) settings and try `tr->langopts.tone_numbers = 1;` or some other settings.
Maybe @michael-conrad may help you, because he made tones from scratch for Cherokee language.

**Comment by jaacoppi** [comment]
Here's some more ideas for debugging:

1. You are getting "m'a1" because the code sets primary stress. This shouldn't happen with tone languages, it should be "ma1". See stress related options in tr_languages.c and compare them to chinese.
 
2. Debug with only one word at a time so the tone sandhi in CalcPitches_Tone() isn't affecting the words.

Check dictsource/cmn_rules. The tones there are 55, 35, 214 and so on.
Check CalcPitches_Tone() in intonation.c. There's code that handles those tones.

3. use -X parameter instead of -x to see which rules are selected.

**Comment by ronaldaug** [comment]
> I'm not experienced with tonal languages. Maybe you can compare [Shan](https://github.com/espeak-ng/espeak-ng/blob/40b78f5183f66958b333d8a54f0ab25a9576be5e/src/libespeak-ng/tr_languages.c#L1585) with e.g. [Chinese](https://github.com/espeak-ng/espeak-ng/blob/40b78f5183f66958b333d8a54f0ab25a9576be5e/src/libespeak-ng/tr_languages.c#L1594) settings and try `tr->langopts.tone_numbers = 1;` or some other settings.
> Maybe @michael-conrad may help you, because he made tones from scratch for Cherokee language.

Thanks for quick reply, I forget to mention that all 6 tones' pitch and sound are working fine. (I can confirm that all the numbers define in `shn_list` sound correctly except the rules `shn_rules` ). The problem is, It doesn't follow in a correct order.  For instance, if I type `လၢမ်း`, normally it should output `la:m4` but currently it outputs `l'a:1m`. Some tones are not following as the last character. 
Anyway, thanks for the help, I will learn Chinese or Vietnam rules first then continuous with this issue again. 


--------------------------

>Here's some more ideas for debugging:

>1. You are getting "m'a1" because the code sets primary stress. This shouldn't happen with tone languages, it should be "ma1". See stress related options in tr_languages.c and compare them to chinese.

>2. Debug with only one word at a time so the tone sandhi in CalcPitches_Tone() isn't affecting the words.

>Check dictsource/cmn_rules. The tones there are 55, 35, 214 and so on.
>Check CalcPitches_Tone() in intonation.c. There's code that handles those tones.

>3. use -X parameter instead of -x to see which rules are selected.

Thanks @jaacoppi , I will try to check `dictsource/cmn_rules`.

**Comment by ronaldaug** [comment]
@valdisvi  Sorry for bothering you again.
Two years ago, I used [espeak-ng online](https://odo.lv/Espeak) without knowledge of git and it was so many conflicts and git errors. So, I want to use it again, could you please reset my repo [https://github.com/ronaldaug/espeak-ng](https://github.com/ronaldaug/espeak-ng) on https://odo.lv/Espeak ?  I use to pull it with a username called "ronald". 

And let me ask one question,
I have a wordlist file which includes all Shan words and it's about 4000 words, Is it a bad idea to add them into `shn_list` like [en_list](https://github.com/ronaldaug/espeak-ng/blob/master/dictsource/en_list) does ? Thanks in advance.
